api/room/schema.py, fixtures/room/room_fixtures.py
- Fix Bug on Get room By Id
- Get room by Id should only return one room object, however, 
for now it returns a list with one room object.
- N/A
- N/A
- #158107020
**Screenshots (if appropriate)**
=> #158107020 Fix get room by Id

api/block/models.py, api/floor/models.py, api/room/models.py, api/room_resource/models.py
- Fix Bug on backward relationship
- For example Get all rooms should return a list of rooms, floor, block, location for particular room 
object.
- N/A
- Executing the query below
allRooms {
id
name
capacity
floorId
}
- Response:
{
"data": {
"allRooms": [
{
"id": "3",
"name": "Gulu",
"capacity": 4,
"roomType": "Meeting Room",
"floorId": 1
},
{
"id": "4",
"name": "Entebbe",
"capacity": 8,
"roomType": "Meeting Room",
"floorId": 1
}
}
With this query it clearly shows that we only have floorId for a given room object which does not satisfy what the frontend mockup need. This means making another query to get more information needed which …
=> #158326634 Enable backward relationship

api/room/schema.py, fixtures/room/room_fixtures.py, tests/test_rooms/test_search_room_by_name.py
- This PR allows users to search room by name
- Test the query at localhost:5000/mrm
- Run `getRoomByName` query
#159461818
`Searching existing room`
`Searching non-existent room`
`Blank input search`
=> #159461818 Search room by name

requirements.txt
include blinker
dependency in requirements
[159622094](<https://www.pivotaltracker.com/n/projects/2154921/stories/159622094>)
=> bug(dependencies): add blinker to requirement.txt file

api/room/schema.py, fixtures/room/room_fixtures.py, tests/test_rooms/test_query_rooms.py
Adds a pagination feature to the rooms query.
Allows queries to be run, with or without pagination.
A user should specify the page number and the items per page when using pagination:
When pagination is not needed, the query needs to be specified as follows:
Create room with the required mutation
Provide pagination's page and perPage as shown in the image above (first image)
To test functionality without pagination, just run the query normally (see second image)
**What are related Pivotal Tracker stories?**
Story: Paginate rooms query
Story ID: #159074707
=> #159074707 paginate rooms query 

api/user/schema.py, fixtures/room/room_fixtures.py, fixtures/user/user_fixture.py, tests/test_rooms/test_search_room_by_name.py, tests/test_user/test_query_user.py
Adds a pagination feature to the users query.
Allows queries to be run, with or without pagination.
A user should specify the page number and the items per page when using pagination:
When pagination is not needed, the query needs to be specified as follows:
Provide pagination's page and perPage on the users query as shown in the image above (first image)
To test functionality without pagination, just run the query normally (see second image)
**What are related Pivotal Tracker stories?**
Story: Paginate users
Story ID: #159629440
=> #159629440 paginate users 

api/room/schema.py, api/user/schema.py, fixtures/room/room_fixtures.py, fixtures/user_role/user_role_fixtures.py, tests/test_user_roles/test_query_user_role.py
Allow users to have an end point from which the admin can change user roles,
such as `Default User` to `Admin` and `Admin` to `Default User`
- Run `changeUserRole` mutation with `email` and `roleId` as  the keyword arguments
When a user performing the action is not an admin.
When a user whose role is being changed is not available.
When the correct user is found.
- https://www.pivotaltracker.com/story/show/159461602
=> #159461602 Change User Roles 

api/room_resource/schema.py, fixtures/room_resource/get_room_resource_fixtures.py, helpers/pagination/paginate.py, tests/test_room_resource/test_get_resource_list.py
This PR enables querying for unique instances of resources
- Run getRoomsInALocation query
#159817747
When no value is passed
When a user set Unique to true
=> #159817747 Add unique filter for resource instances

api/block/schema.py, fixtures/block/block_fixtures.py
Ensures that a list of rooms in a block is returned when the query `getRoomsInABlock` is executed. Previously, the block was returned instead, and not the desired output, rooms.
- Run getRoomsInABlock query
**What are relevant PivotalTracker stories?**
Story: Fix get rooms in block query
Id: #159652407
=> #159652407 fix get rooms in block query

api/office/schema.py, api/wing/schema.py, fixtures/office/office_fixtures.py, helpers/auth/validator.py, helpers/room_filter/room_filter.py, schema.py, tests/test_office/test_get_office_by_name.py
- This PR allows a user to get room by name.
- Run `getOfficeByName` query with specified office name as the argument.
- `Epic tower` office should be able to populate `wings` within a floor from the query.
- `St. Catherine` and `The crest` offices should be able to populate `blocks` and `floors` from the query.
#159960430
=> #159960430 get office by name

.circleci/config.yml
This PR ensures the temporary use of andela-learning project on Google Cloud Platform
**Description of Task to be completed?**
Project should be deployed to `andela-learning` instead of `learning-map`
#160128227
=> #160128227 Make temporary use of andela-learning project on Google Cloud Platform(GCP) for converge backend.

api/office/schema.py, fixtures/location/all_locations_fixtures.py, fixtures/office/office_fixtures.py, helpers/auth/admin_roles.py, schema.py, tests/base.py, tests/test_office/test_delete_office.py
- This PR allows an admin to delete an office within his location.
- Test the mutation at localhost:5000/mrm
- Run `deleteOffice` mutation with an `officeId` as the argument.
#160235030
=> #160235030 Delete office mutation

api/role/schema.py, api/user/schema.py, fixtures/role/role_fixtures.py, fixtures/user/user_fixture.py, helpers/auth/error_handler.py, helpers/auth/validator.py, tests/test_role/test_create_role.py, tests/test_user/test_create_user.py
This PR handle conflict/duplication error for already existing Roles and Users
- Run createUser mutation with an existing user email
- Run createRole mutation with an existing role name
[Error handling](https://www.pivotaltracker.com/n/projects/2154921/stories/160193993)
=> #160193993 Add error handling for Roles and Users

api/room/schema.py, fixtures/helpers/decorators_fixtures.py, fixtures/room/create_room_fixtures.py, fixtures/room/create_room_in_block_fixtures.py, helpers/auth/verify_ids_for_room.py, tests/test_rooms/test_create_room.py
Enable `createRoom` mutation for Nairobi to include `blockId`, and `createRoom` mutation for Lagos to include `wingId` when admin creates a meeting room
- Clone this branch in your local machine, Run the server
- Run `createRoom` mutation with `blockId` when the office is Nairobi or `wingId` when the office is Lagos in the keyword arguments
https://www.pivotaltracker.com/story/show/160127115
When an admin runs the mutation with block id.
When an admin runs the mutation with wing id.
=> #160235195 Update Create Room Mutation to include Block_id and Wing_id

api/room/schema.py, fixtures/room/room_analytics_fixtures.py, helpers/calendar/analytics.py, tests/base.py, tests/test_rooms/test_room_analytics.py
- Handles Analytics of the most used room in a month
- Test query at `localhost:5000/mrm`
- Run `mostUsedRoomPerMonthAnalytics` query using parameters: `month`, `year` and `locationId`
[#160447468](https://www.pivotaltracker.com/story/show/160447468)
- Analytics for most used room in Location1 - Kenya
- Analytics for most used room in Location2 - Uganda
- Response when month selected has no events booked
=> #160447468 Analytics of the most used room in a month

helpers/calendar/analytics.py, tests/test_rooms/test_room_analytics.py
This PR handle analytics for the least used room per week
- Run `analyticsForRoomLeastUsedPerWeek` query with following params.  
- `locationId`
- `weekStart`
- `weekEnd`
[Analytics for the least used room per week](https://www.pivotaltracker.com/n/projects/2154921/stories/160445879)
=> #160445879 Analytics for the least used room per week

api/room/schema.py, fixtures/room/room_analytics_fixtures.py, helpers/calendar/analytics.py, tests/test_rooms/test_room_analytics.py
- This PR enables admins see the statistics of meetings per room i.e count of all meetings per room.
- Run `analyticsForMeetingsPerRoom` query with `locationId`, `dayStart`, and `dayEnd`  as the arguments.
#160445644
=> #160445644 Analytics for meetings per room.

api/room/schema.py, fixtures/room/room_analytics_fixtures.py, helpers/calendar/analytics.py, tests/test_rooms/test_room_analytics.py
This PR enables admins to see the statistics of the least used room per month
- Test the query at `localhost:5000/mrm`
- Run `analyticsForLeastUsedRoomPerMonth` query with `locationId`, `month`(First 3 letters), and `year` as the arguments.
[#160447363](https://www.pivotaltracker.com/story/show/160447363)
=> #160447363 Analytics for least used room per month

api/room/schema.py, fixtures/room/filter_room_fixtures.py, helpers/room_filter/room_filter.py, tests/test_rooms/test_room_filter.py
This PR enables users to filter rooms by location, capacity and office
Run the server
Test the queries at localhost:5000/mrm
#160819518
=> #160819518 Filter roooms by office

api/block/models.py, api/floor/models.py, api/office/models.py, api/room/models.py, api/room_resource/models.py, fixtures/devices/devices_fixtures.py, fixtures/office/office_fixtures.py, tests/base.py, tests/test_office/test_delete_office.py
- This PR adds the cascade effect on delete office to ensure all data related to an office is deleted when an office is deleted.
- Run `deleteOffice` mutation with `officeId` as an argument.
#160845129
=> #160845129 Add cascade effect on  delete office

api/room/schema.py, fixtures/room/room_analytics_fixtures.py, helpers/calendar/analytics.py, tests/test_rooms/test_room_analytics.py
Enable admin to know the most used room(s) per week i.e meeting room(s) with the highest bookings
- Clone this branch in your local machine, Run the server
- Run `analyticsForRoomMostUsedPerWeek` query with `locationId` and the duration range of one week as the keyword arguments as shown in the screen shot below.
[#160447415](https://www.pivotaltracker.com/story/show/160447415)
When an admin runs the query with `locationId`.
When there are no events is a period.
=> #160447415 Analytics for most used room(s) per week

api/room/schema.py, tests/test_rooms/test_create_room.py
-  Fixes room creation duplication error that arises in Kampala and Lagos offices.
- Test the mutation at `localhost:5000/mrm`
- Run `createRoom` mutation using an existing room name in any location
[#160193943](https://www.pivotaltracker.com/story/show/160193943)
First creation
Duplicate creation
Creation of a room in a non-existent block
=> #160193943 Fix room creation duplication error.

tests/base.py, tests/test_office/test_create_office.py, tests/test_office/test_delete_office.py, tests/test_office/test_get_office_by_name.py, tests/test_office/test_update_office.py, tests/test_room_resource/test_create_room_resource.py, tests/test_room_resource/test_delete_resource.py, tests/test_room_resource/test_update_room_resource.py, tests/test_rooms/test_analytics_total_daily_durations.py, tests/test_rooms/test_create_room.py, tests/test_rooms/test_delete_room.py, tests/test_rooms/test_room_analytics.py, tests/test_rooms/test_room_filter.py, tests/test_rooms/test_search_room_by_name.py, tests/test_rooms/test_update_room.py
- Creates a class for common test cases to allow the reuse of one code snippet.
- Create a class that contains methods for the most used test cases
- Refactor tests to call these methods and pass their unique parameters for testing
- Change your `.env` file's app settings to `testing`
- Go to your terminal and enter the `mrm_api` folder
- Run `$ source .env`
- Run `$ tox`
- Wait for all tests to pass 
[#160949212](https://www.pivotaltracker.com/story/show/160949212)
=> #160949212 Fix Backend Tests to Remove Duplication

api/user/schema.py, fixtures/user/user_fixture.py, helpers/auth/error_handler.py, helpers/auth/validator.py, tests/test_user/test_change_user_role.py
- This PR fix error in the change user role mutation when a role id that does not exist is passed as an argument.
- Run `changeUserRole` mutation with `email` and `roleId` as arguments.
#160993422
=> #160993422 Fix change of user role mutation

api/room/schema.py, fixtures/room/room_analytics_daily_duration_fixtures.py, fixtures/room/room_monthly_meeting_duration_fixtures.py, helpers/calendar/analytics.py, tests/test_rooms/test_room_analytics.py
Enable admin to know the total meeting duration for each room within a specific month.
- Clone this branch in your local machine, Run the server
- Run `monthlyDurationsOfMeetings` query with `locationId`, `month` and `year` as the keyword arguments as shown in the screen shot below.
[#160447638](https://www.pivotaltracker.com/story/show/160447638)
When an admin runs the query with locationId, year and month.
=> #160447638 Analytics for total monthly meetings duration

api/room/schema.py, fixtures/room/room_analytics_fixtures.py, helpers/calendar/analytics.py, tests/test_rooms/test_room_analytics.py
- This PR enables admins see the least used room per day.
- Run `analyticsForLeastUsedRoomPerDay` query with `locationId` and `day`  as the arguments.
#160447342
=> #160447342 Analytics for least used room per day

api/room/schema.py, fixtures/helpers/decorators_fixtures.py, fixtures/room/create_room_in_block_fixtures.py, helpers/auth/validator.py, helpers/auth/verify_ids_for_room.py, tests/test_rooms/test_create_room.py
Allows Admins to create rooms in Kampala and Lagos Offices without passing a `Block ID`. But it required for the Nairobi Office
#161179201
I disabled the admin's location to able to test for Lagos and Nairobi
Creating a room in Kampala Office without a `Block ID`
Creating a room in Kampala Office with a `Block ID`
Creating a room in Nairobi Office without a `Block ID`
Creating a room in Nairobi Office with a `Block ID`
Creating a room in Lagos Office with a `Wing ID` but no `Block ID`
=> #161179201 Fixes Room Creation making block ID required for Nairobi Office only

helpers/calendar/analytics_helper.py
Fix analytics mutation that returns an empty list instead of the correct analytics requested
- Run the analytics mutations for most and least used rooms  
#161506663
=> #161506663 fix analytics response

schema.py
Enables a user to set his/her device health email notification preference to either True or False.
- Run migrations.
- Run the `getUserNotificationSettings` query with `userId` as the argument.
- Run the `updateNotification` mutation with `deviceHealthNotification` as the argument.
[#161279850](https://www.pivotaltracker.com/story/show/161279850)
1. _Query for a non-existing user_
2. _Query for an existing user_
3. _Mutuation for a user_
=> #161279850 users should be able to set email notification preferences.

api/analytics/analytic_report.py, api/analytics/analytics_request.py, api/analytics/write_files.py, requirements.txt
-  Exports room analytics report as JPEG
- Ensure to install wkhtmltoimage and  wkhtmltopdf by running the command: `brew install Caskroom/cask/wkhtmltopdf` on your terminal.
- Test the mutation at `localhost:5000/analytics`
- Make a POST request using json input containing: `timeMin`, `timeMax`, `fileType`: "JPEG"
- Download the file generated and view.
[#161054985](https://www.pivotaltracker.com/story/show/161054985)
1. Request and Output
2. Downloaded Image
3. Response when no file format is specified
=> #161054985 Export analytics report as JPEG 

api/room/models.py, fixtures/helpers/decorators_fixtures.py, fixtures/room/create_room_fixtures.py, helpers/auth/validator.py, tests/test_rooms/test_create_room.py, tests/test_rooms/test_room_model.py
This PR adds an event listener for calendar Ids to ensure only rooms with valid calendar Ids are save in the database when creating a room.
- Run the `createRoom mutation` with an invalid calendar id.  
#161481601
=> #161481601 add event listener for calendar id during room creation

api/notification/schema.py, fixtures/notification/notification_fixture.py, tests/test_notification/test_query_notification.py
Allows a the front end to send a query without the UserId parameter
- Remove the userId field from the query
- Retrieve the userId using the token
- Refactor tests and fixtures
- Run server `http://127.0.0.1:5000/mrm`
- Run the `getUserNotificationSettings` without a userId
- It should return the user notification settings
[#161623168](https://www.pivotaltracker.com/story/show/161623168)
=> #161623168 Enable a query for notifications without a userId parameter

api/analytics/analytic_report.py
Allows admins to get analytics for the top ten most and least used rooms. In case of a tie, the number of returned results adjusts appropriately.
- Call the `/analytics` endpoint passing the `start_date`, `end_date` and the `file_type`(optional).
What are the relevant pivotal tracker stories?
[#161279850](https://www.pivotaltracker.com/story/show/161645315)
=> #161279850 Update analytics to show the top ten most and least used  rooms.

api/analytics/analytics_request.py, api/room/schema.py, api/room/schema_query.py, fixtures/room/room_analytics_duration_fixtures.py, fixtures/room/room_analytics_least_used_fixtures.py, fixtures/room/room_analytics_most_used_fixtures.py, fixtures/room/room_monthly_meeting_duration_fixtures.py, helpers/calendar/analytics.py, helpers/calendar/analytics_helper.py, tests/test_rooms/test_room_analytics.py
This PR refactor analytics to use a date range and make `endDate` argument optional to be able to handle a single day analytics
- Run the following queries with `startDate` and `endDate` arguments:  
- `analyticsForMostUsedRooms`
- `analyticsForLeastUsedRooms`
- `analyticsForMeetingsPerRoom`
- `analyticsForMeetingsDurations`
[Refactor analytics](https://www.pivotaltracker.com/n/projects/2154921/stories/161615830)
=> #161615830 refactor analytics to use a date range

api/room/schema_query.py
- Updates events model and Enables an admin to obtain the ratio of check-ins to booked meetings
- First,  Run migrations to update Events model. 
- Test the mutation at `localhost:5000/mrm`
- Run `eventCheckin` mutation to have a checkin record in the db to facilitate analytics ratio.
- Run `analyticsRatios` query with `start_date` and `end_date` as the parameters
[#160491334](https://www.pivotaltracker.com/story/show/160491334)
1. EventCheckin mutation
2. Checkins to bookings ratio query
=> #160491334 Generate ratio of check-ins to booked meetings

api/analytics/analytic_report.py, helpers/calendar/analytics_helper.py
- A descriptive message is returned to the user in case rooms do not exist in that location.
- Correct analytics report for rooms with zero meeting.
- Test endpoint (JSON) `http://127.0.0.1:5000/analytics`
- Ensure room with zero meeting should return 0 not 1 analytics report
[#161749506](https://www.pivotaltracker.com/story/show/161749506)
`JSON Error Message`
=> #161749506 Error Handling & correct analytics export report

api/user_role/schema.py
It ensures that a user role can only be created once, and if one tried to create the same user role again, then it returns a descriptive error message
-Test the queries at `localhost:5000/mrm`
-Run the following query: 
`createUsersRole`
It should be successful when you run it once but should fail on the second run
What are the relevant pivotal tracker stories?
[#161676333](https://www.pivotaltracker.com/story/show/161676333)
=> #161676333 fix create user role duplication

api/analytics/analytic_report.py, api/analytics/analytics_request.py, api/analytics/write_files.py
- Allows the REST endpoint to return the HTML code for the analytics table as a string so they can convert it to JPG or PDF
- On the endpoint `http://127.0.0.1:5000/analytics`, send a post request with the following parameters `start_date`, `end_date` and `filetype: html`
[#162269808](https://www.pivotaltracker.com/story/show/162269808)
=> #162269808 Allow the html code to be returned as a string 

api/block/schema.py, fixtures/block/create_block_fixtures.py, helpers/auth/admin_roles.py, helpers/room_filter/room_filter.py, schema.py, tests/test_block/test_create_block.py
Admin updates & delete blocks in the Nairobi office.
- Test the mutation at localhost:5000/mrm
- Run `updateBlock` - updating block and `DeleteBlock` for deleting block
[#162157772](https://www.pivotaltracker.com/story/show/162157772)
_Update block_
_Delete block_
=> #162157772 Enable Admin update & delete block in Nairobi

api/room/schema_query.py, fixtures/room/room_analytics_duration_fixtures.py, helpers/pagination/paginate.py, tests/test_rooms/test_analytics_total_durations.py
Enables a user to get paginated results from the meeting room duration analytics.
- Run the `analyticsForMeetingsDurations` query with `startDate`, `endDate`(optional), `page` and `perPage` as the arguments.
What are the relevant pivotal tracker stories?
[#162158635](https://www.pivotaltracker.com/story/show/162158635)
1. _Query without pagination details specified_
2. _Query with a valid page argument and a valid perPage argument_
3. _Query with an invalid page argument and a valid perPage argument_
=> #162158635 users should be able to get paginated results from the meeting room duration analytics.

api/block/models.py, api/block/schema.py, fixtures/block/block_fixtures.py, fixtures/block/create_block_fixtures.py, fixtures/location/all_locations_fixtures.py, fixtures/office/office_fixtures.py, fixtures/office/update_delete_office_fixture.py
- Adds create block mutation to enable an admin to create blocks in the Nairobi office.
- Test the mutation at `localhost:5000/mrm`
- Run `createBlock` mutation with the parameter 'room_id'  and 'name', as  required parameters
[#162054093](https://www.pivotaltracker.com/story/show/162054093)
1. Create block
2. Try duplicate same block name
3.Create block without name
4. Try to create a block that is not in the Nairobi office
5. Error message for the non-existent office
=> #162054093 Enable admin create blocks in Nairobi office

api/user/schema.py, fixtures/user/user_fixture.py, helpers/user_filter/user_filter.py, tests/test_user/test_query_user.py
- Allows the filtering of users by their location and their role
- Run the server and use the URL `localhost:5000/mrm`
- Run the query `users` to retrieve Paginated Users with the parameter `locationId`. This should return the users in the location specified
- Run the query `users` to retrieve Paginated Users with the parameter `roleId`. This should return the users with the specified role
[#162444849](https://www.pivotaltracker.com/story/show/162444849)
**Get users by their location**
**Query a non-existent or unused location/role**
**Query users by their role**
**Query users by their role and location**
=> #162444849 Add functionality to sort users by location and role

api/room/schema.py, api/room/schema_query.py, fixtures/room/room_analytics_bookings_count_fixtures.py, helpers/calendar/analytics_helper.py, helpers/calendar/ratios_and_utilization.py, tests/test_rooms/test_room_analytics.py
- Enables a user to get analytics for the total number of bookings(daily and monthly).
- If the date range is less than 15 days, you get the total number of bookings for each day.
- If the date range is greater than 90 days, you get the total number of bookings for each month.
Run the server `http://127.0.0.1:5000/mrm`.
Run the `bookingsAnalyticsCount` query with `startDate` and `endDate`(both are required fields).
[#162299447](https://www.pivotaltracker.com/story/show/162299447)
1. Get analytics for a date range that is less than 15 days.
2. Get analytics for a date range that is greater than 90 days.
3. Get analytics for an invalid date range.
=> #162299447 users should be able to get analytics for the total number of bookings(daily and monthly).

api/analytics/analytic_report.py, api/analytics/write_files.py, helpers/calendar/analytics_helper.py
- Change the analytics date to a readable format
- Run the server on `http://127.0.0.1:5000/analytics`
- Make the following request:
> {
"start_date": "Oct 8 2018",
"end_date": "Oct 15 2018",
"file_type": "pdf"
}
https://www.pivotaltracker.com/story/show/162631160
**New Date Format**
**Old Date Format**
=> #162631160 Change date for analytics report to a readable format

api/question/schema.py, fixtures/questions/create_questions_fixtures.py, tests/test_questions/test_create_question.py, utilities/utility.py
- Allows an admin to add a startTime and endTime to a question
```mutation {
createQuestion(questionType:"Rate",
question:"How will you rate the brightness of the room",
startDate:"2018-12-20T23:42:43", endDate:"2018-12-28T15:42:43") {
question{
id
question
questionType
startDate
endDate
}
}
}
```
[#162727868](https://www.pivotaltracker.com/story/show/162727868)
=> #162727868 Enable admin add time to a question being created

api/floor/schema.py, fixtures/floor/filter_by_block_fixtures.py, tests/test_floors/test_filter_by_block.py
-  Enables an admin to filter floors by block
**Description of task to be completed**
- Ensure that as an admin I can filter the floors by blocks
- Run the `filterByblock` query  passing a `blockId` that is oresent in the datbase as shown below
```
query {
filterByBlock(blockId: 1){
id
name
blockId
}
}
```
[#162241777](https://www.pivotaltracker.com/story/show/162781153)
=> #162781153 Filter floors by block

api/response/schema.py, fixtures/response/user_response_check.py, schema.py, tests/test_response/test_user_response.py
-  Enables an admin to filter feedbacks per room
```
{
getRoomResponse(roomId: 1) {
room {
id
feedback {
id
userId
cleanlinessRating
comments
}
}
}
}
```
[#162241777](https://www.pivotaltracker.com/story/show/162241777)
=> #162241777 Admin can filter feedbacks  per room

api/response/models.py, api/response/schema_query.py, fixtures/questions/get_question_fixtures.py, fixtures/response/room_response_fixture.py, fixtures/response/user_response_check.py, fixtures/response/user_response_fixtures.py, fixtures/response/user_response_suggestions.py, schema.py, tests/base.py, tests/test_response/test_room_response.py
- Allow Admin to view individual responses in a room.
- Test the query at `localhost:5000/mrm`
- Run `roomResponse` query with the parameter `room_id`
[#162241130](https://www.pivotaltracker.com/story/show/162241130)
1. Response for Non-existence roomID
2. Room response for valid room ID
=> #162241130: View Individual responses from a room

api/response/schema_query.py, fixtures/response/room_response_fixture.py, tests/test_response/test_room_response.py
- Admin is able to view the total tool availability of a room (missing tools) and the additional feedback given per room (comments given per room).
**Description of task to be completed**
- As an admin, I want to view the details of tool availability and additional comments feedback question, so that I can be able to see the response summaries from all the rooms on which these two questions were asked.
The data returned is response data in all rooms. The aggregate data e.g the number of missing items will be done in the front-end.
- Add questions using the questions mutation
- Provide feedback to any rooms available i.e rating, report any …
=> #162572539 Enable admin to view tool availability and additional feedback

api/location/schema.py, fixtures/location/create_location_fixtures.py, requirements.txt, utilities/utility.py
* Add Validations to imageUrl and location name.
* Added validations that ensure the string put as the imageUrl is a valid url and also the location name should be a valid name like Nairobi or Lagos.
* git checkout to `bg-validate-image-location-name-163066222`, `pip install validators`  and run the following mutation:
```
mutation {
createLocation(name: "Kampala", abbreviation: "KLA", country: "Uganda", timeZone: "EAST_AFRICA_TIME") {   # noqa E501
location {
name
}
}
}
```
```
mutation{
updateLocation(locationId: 1, name: "Nairobi", country: "Kenya", abbreviation: "KE",imageUrl:"http://image.com"){ # noqa: E501
location{
name
abbreviation
country
}
}
}
```
* play with name and imageUrl in …
=> #163066222 make validations to image and name

api/question/models.py, api/question/schema.py, api/response/models.py, fixtures/questions/get_question_fixtures.py, schema.py, tests/test_questions/test_view_question.py
Allows Admins to see the number of responses to a particular feedback question.
- Run the `questions` query to get all the questions. Each question will have a `questionResponseCount` attribute showing the total number of responses to that particular question.
- Run the `questions` query passing `page` and `perPage` as arguments for pagination. Each question will have a `questionResponseCount` attribute showing the total number of responses to that particular question.
- Run the `question` query passing the `id` as an argument. The question will have a `questionResponseCount` attribute showing the total number of responses to that particular question.
**What are the relevant pivotal …
=> #162730598 Allow Admins to see the number of responses to a particular feedback question.

api/location/schema.py, fixtures/location/create_location_fixtures.py, fixtures/location/update_location_fixtures.py, tests/test_location/test_create_location.py, tests/test_location/test_update_location.py
- Solves the issue of creating multiple locations with similar names
At the moment, one can create multiple rooms with similar names. This should not be the case since it might lead to conflicts.
- Run the following query twice
```
mutation {
createLocation(name: "TestLocation", abbreviation: "KLA", country: "Kenya", timeZone: "EAST_AFRICA_TIME") {
location {
name
}
}
}
```
**initial creation of a location**
**duplicate creation of a room**
**duplicate creation of the same room with different cases**
[#163055834](https://www.pivotaltracker.com/story/show/163055834)
=> #163055834 Fix add location bug

api/response/schema_query.py, fixtures/response/room_response_fixture.py, tests/test_response/test_room_response.py
- Have implementation of filtration of rooms by the number of responses
- Have the implementation of a query that accepts three arguments `filterBy` `upper_limit` and `lower_limit` and returns the rooms whose total response is within the range of the two. The rationale fot the filterBy filed is to allow the same field to be used by another developer in the future who requires to filter the responses by a different metric. I had to change the response schema_query to include the filter since this is where the code for the room responses is. I also introduced a fixture file that contains the data that I will use for testing the query I created. Finally introduced a test file that tests the functionality of the introduced query. This ensures that if any other developer were to break the code …
=> #163111433 Enable admin to filter room responses by number of responses

api/location/models.py, api/location/schema.py, fixtures/location/delete_location_fixtures.py, tests/test_location/test_delete_location.py
* Admin should be able to delete a location that is not used anymore.
*  Added delete fuction to the `api/location/schema.py` file.
* Added mutations and expected responses to the `fixtures/locations/delete_location_fixtures.py`
* Added tests to `tests/test_location/test_delete_location.py`
* git checkout to `ft-admin-delete-location-163371157` and run the following mutation:
```
mutation {
createLocation(name: "Kampala", abbreviation: "KLA", country: "Uganda", timeZone: "EAST_AFRICA_TIME") {   # noqa E501
location {
name
}
}
}
```
```
mutation{
deleteLocation(locationId:1){
location{
id
}
}
}
```
* The above mutation is assuming the location you created is of `id` 1, otherwise the `id` should …
=> #163371157 Admin delete unused location

alembic/versions/c8a866f85fd7_decouple_device_and_resource_entity.py
- It removes the non-existant down-revision file and replaces it with one that exists
- Currently, the down-revision file in the `decouple resource and device entity`  doesn't exist.  This PR adds a file that exists
- Checkout from develop after pulling latest changes.
- Run migrations `make migrate message="Migration Message"`
- None
[#163518080](https://www.pivotaltracker.com/story/show/163518080)
=> #163518080 Fix alembic migrations on develop:

api/office/schema.py, helpers/email/email.py
- It sends an email notification to the admin that creates an office and not all admins
- At the moment, when an admin creates an office, all admin receive the email notification.
- Create two admin in your database
- Create a new office by running `createOffice` mutation
- None
[#163391935](https://www.pivotaltracker.com/story/show/163391935)
=> #163391935: Fix Email notification bug

fixtures/floor/get_floors_fixures.py, helpers/pagination/paginate.py, tests/test_floors/test_query_floors.py
Add current page on paginator
- The current page number is added to the paginator
- Modify the fixtures to cover the added lines
- checkout branch `ft-add-current-page-163219021`
- Run  the application using `make run-app`
- Query any paginated data say rooms.
The current paginator indicates whether a page has_next or has_previous but does not indicate the current page. 
[#163219021](https://www.pivotaltracker.com/story/show/163219021)
=> #163219021 Add current page on paginator

api/question/schema.py, fixtures/questions/create_questions_fixtures.py, tests/test_questions/test_update_question.py
The PR enables the converge team keep track of the number of views on the feedback questions
Currently, the team does not know if people using the rooms view the questions but do not send back any feedback.  The PR raised seeks to remedy that by introducing a counter that increments everytime the `feedback` button is pressed on the Android platform.
- Run the following query.
```    mutation{
updateQuestionViews(incrementTotalViews:true) {
questions{
id
question
totalViews
}
}
}
```
- The PR answers the request of the Fellow Project Coordinator to see those who view the feedback questions but do not give any feedback.
[#162576320](https://www.pivotaltracker.com/story/show/162576320)
=> #160609522 Record when room-feedback-questions are viewed

helpers/calendar/analytics_helper.py
* Handle all 404 error message when the resource for bookings analytics counts is not found.
*  Added an exception handler to the `analytics_helper.py` file
* git checkout to `ch-handle-HTTP-errors-163189549` and run the following query:
* Run the `bookingsAnalyticsCount` query with `startDate` and `endDate`(both are required fields).
* Not applicable
* previous error message when a wrong calendar id is supplied
* new error message when a wrong calendar id is supplied
[#163189549](https://www.pivotaltracker.com/story/show/163189549)
=> #163189549 Implement error handling for missing resource

api/room/models.py, api/tag/models.py, api/tag/schema.py, fixtures/tags/create_tags_fixtures.py, schema.py, tests/base.py, tests/test_tags/test_create_tags.py
Enable an admin to create tags
Create a mutation to enable admins to create tags of various rooms
* git checkout to `ft-admin-create-tag-163355551` and run the following mutation:
```
mutation {
createTag (name: "BlockA", color: "blue", description: "Block") {
tag {
name,
color,
description
}
}
}
```
* On creating a room, an admin can add one or more tags to a room.
This is what one expects to see on creating a mutation:
On creating a tag with a name that already exists:
On creating a tag without the required arguments
[#163355551](https://www.pivotaltracker.com/story/show/163355551)
=> #163355551: Enable admin to create tags

api/office/schema.py, helpers/email/email.py, templates/office_success.html
- Adds office location to the email sent to the admin on creating an office
- Currently, when an office is created, an admin receives an email with just the name. This PR adds the location where the office was created.
- Create an office
- You should be able to receive an email with both the name of the office and the location.
**Before**
**After**
[ #163391842 ](https://www.pivotaltracker.com/story/show/163391842)
=>  #163391842 Add office location on email sent on office creation

api/room/schema_query.py, fixtures/room/daily_room_events_fixture.py, helpers/calendar/events.py, tests/test_rooms/test_daily_room_events.py
- Ensure that the admin is able to get the events happening on certain dates
- To get the events between certain dates you have to query google API for events in all the rooms currently in the database between those days.
-  The data has to be filtered to have only the data that we require which is the event summary, start and end times, room where the event is taking place.
- Provide an endpoint for the query to be send and have the data returned
- Finally write tests to test all the implemented functionality.
- Pull this branch
-  Run the `https://127.0.0.1:8000/mrm[POST] endpoint on insomnia
- Run the following query 
```
query{
analyticsForDailyRoomEvents(startDate:"jan 10 2019", endDate:"jan 10 2019"){
day
events{
eventSummary
startTime
endTime
roomName
noOfParticipants
}
}
}
```
The …
=> #163388031 Enable admin to view daily events

api/analytics/analytic_report.py, api/room/schema.py, fixtures/events/events_ratios_fixtures.py, helpers/calendar/analytics.py, helpers/calendar/analytics_helper.py, helpers/calendar/ratios_and_utilization.py
- Enables the admin to see app bookings percentage
The task is to admin to view the percentage of bookings that were made from the mobile app. 
- Then run either of the following queries:
```
query {
analyticsRatios(startDate: "Dec 09 2018", endDate: "Jan 17 2019") {
checkins
cancellations
bookings
roomName
appBookings
}
}
```
```
query {
analyticsRatiosPerRoom(startDate: "Dec 09 2018", endDate: "Jan 17 2019") {
ratios {
bookings
checkins
cancellations
appBookings
roomName
}
}
}
```
- You will see the app bookings percentage returned.
None
**What are the …
=> #163456848 Enable admin to view the app bookings percentage

api/block/schema.py, api/devices/schema.py, api/floor/schema.py, api/location/schema.py, api/office/schema.py, api/question/schema.py, api/room/schema.py, api/room_resource/schema.py, api/tag/schema.py, api/wing/schema.py, fixtures/tags/create_tags_fixtures.py, tests/test_tags/test_create_tags.py, utilities/utility.py, utilities/validations.py
Allows admins to update/edit tags
Currently, tags can be created but not edited, this PR adds a mutation to enable this.
Pull the changes after checking out to a new branch from Develop.
Run the mutation for creating a tag.
Run the following query to edit the tag created, using the tag's id.
``` 
mutation {
updateTag (tagId: 1, color: "grey") {
tag {
name,
color,
description
}
}
}
```
The response should be similar to that shown in the screenshots.
The fail on codeclimate is due to code not related to these changes.
[#163356514](https://www.pivotaltracker.com/story/show/163356514)
=> #163356514 Enable admin to update/edit tags

api/room/schema.py, fixtures/helpers/decorators_fixtures.py, fixtures/room/create_room_with_tags_fixtures.py, fixtures/room/room_fixtures.py, tests/base.py, tests/test_rooms/test_room_crud_with_tags.py
Allows admins to include tags in room CRUD operations i.e Creating rooms and Updating rooms.
Admin's adding and editing rooms should select tags that are to be associated with the room. Deleting rooms should remove the relationship between the room and tags.
* git checkout to `ft-implement-tags-in-rooms-163584006` and run the following mutations:
Create room:
```
mutation {
createRoom(
name: "Room 2", roomType: "Meeting", capacity: 4, floorId: 2, officeId: 1, roomTags: [1, 3],
calendarId:"andela.com_3836323338323230343935@resource.calendar.google.com",
imageUrl: "https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg") {  
room {
id
name
roomType
capacity
floorId …
```
=> #163584006 Implement tags on Room CRUD operations

api/room/schema_query.py, tests/test_authentication/test_authentication.py
- Allow non-admins to view analytics data
- A default user should be able to view the analytics data i.e the piecharts, graphs, and tables that are currently viewable by admins only.
- pull and checkout branch `bg-allow-non-admins-view-analytics-163391316`
- create a default user in the database 
- log into the system with that default user
- provide that user's token in the headers
- run query in the screenshot below or any other query that involves retrieving analytics data.
[#163391316](https://www.pivotaltracker.com/story/show/163391316)
=> #163391316 Allow non-admins to view analytics data

api/response/schema_query.py, fixtures/response/room_response_fixture.py
Adds room Id field to query all room responses.
`allRoomResponses` should be returned with the `roomId`, `roomName`, `response`, and `totalResponses` for each particular room
N/A
* pull and checkout branch `bg-add-room-id-to-room-responses-163756241`
* run the app using `make run-app`
* run the query below
```
query{
allRoomResponses(filterBy:"Responses",upperLimit: 2, lowerLimit: 0 ){
responses{          
totalResponses
roomId
roomName          	
response{
responseId
missingItems
}
}
}
}
```
expected response
```
{
"data": {
"allRoomResponses": {
"responses": [
{
"totalResponses": 0,
"roomId": 1076,
"roomName": "TestRoom",
"response": []
},
{
"totalResponses": 0,
"roomId": 168,
"roomName": "Conakry",
"response": []
}
]}
}
}
```
[#163756241](https://www.pivotaltracker.com/story/show/163756 …
=> #163756241 Add room Id field to allRoomResponses query

api/response/schema_query.py, fixtures/response/room_response_fixture.py, fixtures/room/room_fixtures.py, tests/test_response/test_room_response.py
- Allow admin to search for room feedback response using the room name
- Add an option to search response by room name in the response schema query
- Updated the test file for search functionality
- Test the query at `localhost:8000/mrm`
- Run `allRoomResponses ` query. Sample query can be found [here](https://github.com/andela/mrm_api/blob/develop/fixtures/response/room_response_fixture.py)
[#163725518](https://www.pivotaltracker.com/story/show/163725518)
1. Room Responses filter by responses and search by room name
2. Room responses filter by responses and search by room name beyond limits
3. Room responses search by room name only
4. Room response search by invalid room name
5. Room response filter by response and search invalid room name
=> #163725518:Allow admin to search feedback response by room name

api/response/schema.py, fixtures/response/user_response_check.py, fixtures/response/user_response_fixtures.py, fixtures/response/user_response_suggestions.py, tests/test_response/test_user_response.py
- Allows creation of a response for multiple questions
Change question id to allow a list of integers
Modify tests accordingly
```
mutation {
createResponse(questionId: 1, roomId: 164, rate: 1, textArea: "empty", missingItems: [65]) {
response {
roomId
questionId
question {
question
}
}
}
}
```
```
mutation {
createResponse(questionId: [2, 3, 1], roomId: 164, rate: 1, textArea: "empty", missingItems: [65]) {
response {
roomId
questionId
question {
question
}
}
}
}
```
None
[#163731044](https://www.pivotaltracker.com/story/show/163731044)
Before bug fix
After bug fix
_`with valid ids`_
_`with some invalid ids`_
**Questions:**
None
=> #163731044 Fix create response mutation

fixtures/events/events_ratios_fixtures.py, helpers/calendar/ratios_and_utilization.py, tests/test_events/test_event_checkin.py
The PR increases the number of decimal places of the cancellation percentage.
It also adjusts the function used to return the percentage to make it a member of the class in which it had been placed.
In regards to the assertion added in the associated tests file, the line that returns the percentage is not covered and the assertion resolves this.
Enable a more accurate figure to be returned when running analytics rations, more especially cancellationsPercentage.
Pull the branch and create an odd number of events with a valid calender_id corresponding to a room_id in the local database.
Run the mutation below with corresponding dates for the events created.
``` 
query {
analyticsRatios (startDate: "Jul 05 2018", endDate: "Jul 16 2018") {
cancellations
appBookings …
```
=> #163653690 Fix cancellation percentage accuracy

api/room/schema_query.py, fixtures/room/most_booked_room_least_booked_rooms_fixtures.py, helpers/calendar/analytics.py, helpers/calendar/analytics_helper.py, tests/test_rooms/test_most_booked_least_booked.py
* Refactor analytics code that using REST to start using GraphQL so that we can have a one API, which is GraphQL served. 
*  Added a function to `helpers/calendar/analytics.py` to calculate percentage and room meetings per room.
* Added resolvers to `api/room/schema_query.py` to get mutations for top ten and bottom ten most booked rooms per a varied period.
* git checkout to `ft-graphql-endpoints-for-most-booked-least-booked-rooms-16364677` and run the following query:
```
{
analyticsForMostBookedRooms(startDate:"Jul 1 2018", endDate:"Jul 10 2018")
{
analytics {
roomName
meetings
percentage
}
}
}
```
```
{
analyticsForLeastBookedRooms(startDate:"Jul 1 2018", endDate:"Jul 10 2018")
{
analytics …
```
=> #163646779 Refactor most booked and least booked endpoints from Rest to GraphQL

fixtures/room/room_analytics_bookings_count_fixtures.py, helpers/calendar/ratios_and_utilization.py, tests/test_rooms/test_room_analytics.py
- It enables the user to enter a date range of their choice 
- Remove the restriction to sending a date range that is bellow 15 days and greater than
90 days. This will enable the user to choose the range freely.
- Pull this branch.
- Run the app using `make run-app`
```
query{
bookingsAnalyticsCount(startDate:"jan 2 2019" endDate: "jan 25 2019"){
bookings
period
}
}
```
N/A
[#163729499](https://www.pivotaltracker.com/n/projects/2154921/stories/163729499)
The query response before the fix
The query response after the fix
The query response if the period is greater than 31 days
=> #163729499 Fix analytics date range for bookingsAnalyticsCount query

api/room/schema_query.py, fixtures/room/query_room_fixtures.py, tests/test_rooms/test_query_rooms.py
- Gets the list of rooms from google calendar api
Return all rooms from the google calendar api
```
query {
allRemoteRooms {
rooms {
calendarId
name
}
}
}
```
None
[#163782051](https://www.pivotaltracker.com/story/show/163782051)
**Questions:**
None
=> #163782051 get remote rooms from google calendar api

fixtures/room/room_analytics_duration_fixtures.py, helpers/calendar/analytics.py, helpers/calendar/analytics_helper.py, helpers/calendar/ratios_and_utilization.py, tests/test_rooms/test_analytics_total_durations.py
- This PR is to prevent the admin from selecting a future date range when querying analytics data that is not applicable to a future date.
- Given I am an admin
- When I input a future date range on "% of check-in, % of app bookings, % of auto cancellations and average meeting duration" analytics  
- Then I should get a warning message preventing me from inputting a future date when querying this analytics data
- git pull and checkout branch `ft-limit-date-range-on-analytics-data-163733826`
- run the app using `make run-app`
- query meeting durations analytics data or any other data stated in the description
- here is the sample query
```
query {
analyticsForMeetingsDurations(startDate:"sep 10 6080"){
MeetingsDurationaAnalytics{
roomName
count
totalDuration
events{
durationInMinutes …
```
=> #163733826 Limit the date range on analytics data

api/events/schema.py, fixtures/events/event_checkin_fixtures.py, helpers/calendar/events.py, tests/base.py, tests/test_events/test_event_checkin.py
Make the checkin feature more robust by:
- Only updating `checkin field` to `True` if the event exists in the DB
- Add the event to the DB if it does not exist with checkin set to `True`
- Pull this branch
- make the migrations as explained in the [README](https://github.com/andela/mrm_api/blob/develop/Readme.md)
- create an event and run the following query to check-in into that event
```
mutation {
eventCheckin(calendarId: "your_calendar_id", eventId: "the_event_id", eventTitle: "event_title", startTime: "2019-02-15T01:00:00-08:00", endTime: "2019-02-15T01:30:00-08:00") {
event {
eventId
roomId
checkedIn
cancelled
room {
id
name
calendarId
}
}
}
}
```
* successful check-in into an event
* trying to check-in into an already checked in event
* checking in into a canceled event
N/A …
=> #163849417 Refactor event check-in endpoint

api/response/schema.py, fixtures/response/user_response_check.py, fixtures/response/user_response_fixtures.py, fixtures/response/user_response_suggestions.py, helpers/response/create_response.py, tests/test_response/test_user_response.py, utilities/validations.py
- Allow sending responses as list of objects
- Change mutation to allow sending list of objects
- Modify tests accordingly
```
mutation {
createResponse(responses: [{questionId: 1 textArea: "text here", missingItems: []}, {questionId: 2, rate: 4, textArea: "", missingItems: []}, {questionId: 3, missingItems: [65, 67]}], roomId: 164) {
response {
roomId
questionId
textArea
question {
question
}
}
}
}
```
None
[#163976389](https://www.pivotaltracker.com/story/show/163976389)
_Sending correct mutation
_Sending with an incorrect question id_
**Questions:**
None
=> #163976389 refactor the create response mutation

api/response/schema_query.py, fixtures/response/room_response_fixture.py, tests/test_response/test_room_response.py
Add pagination to room responses 
This is to enable the admin to view the room feedback responses using a paginator, to enable quick scrolling
* git checkout to `ft-paginate-responses-163904284` and run the following mutation:
```
query{
allRoomResponses(page:1, perPage:2){
responses {
roomName,
totalResponses,
response {
responseId,
rating,
suggestion,
missingItems
}
}
hasNext
hasPrevious
pages
}
}
```
The pagination uses the ListPaginate helper function. 
* On querying for room in first page
* If there are no more responses
[#163904284](https://www.pivotaltracker.com/story/show/163904284)
=> #163904284 Add Pagination to all room responses query

api/room/schema.py, fixtures/room/create_room_fixtures.py, fixtures/room/room_analytics_bookings_count_fixtures.py, tests/test_rooms/test_create_room.py
* This PR is to prevent having multiple Rooms with the same `calendar_id` in the database
* Validate the calendar_id provided by the user to ensure that it's unique and applies to exactly one room in the database.
* git pull and checkout branch `bg-creating-multiple-rooms-with-similar-calendar-Id-163817764`
* run the app using `make run-app`
* run a query to create a room
* change the room name and run the same query again.
Example query
````
mutation {
createRoom(
name: "Accra", roomType: "Meeting", capacity: 4, floorId: 5, officeId: 4,
calendarId:"andela.com_3836303335343335373932@resource.calendar.google.com",
imageUrl: "https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg") {  # noqa: E501
room {
name
roomType
capacity
floorId
imageUrl
}
}
}
````
Expected …
=> #163817764 Prevent creating a Room with duplicate calendar Id

api/block/models.py, api/floor/models.py, api/location/models.py, api/office/models.py, api/room/models.py, api/wing/models.py, fixtures/room/room_analytics_bookings_count_fixtures.py, utilities/utility.py
The PR enables the deletion of related data if a delete mutation is used
When deletions are done, related data is not included in the deletion/archiving. As an example, deleting a location will leave the rooms for that particular location still available. This PR enables this to be carried out automatically.
Pull the branch and run a deletion query such as the one of locations below.
``` 
mutation {
deleteLocation(locationId: 1) {
location {
name
}
}
}
```
Any offices and rooms related to the location will also be deleted/archived.
N/A
[#163977386](https://www.pivotaltracker.com/story/show/163977386)
N/A
=> #163783849 Add cascading effect on soft-delete feature

.gitignore, helpers/auth/authentication.py, tests/test_authentication/test_authentication.py
* Mock Andela Api instead of making actual requests to it during testing. 
*  Since we are using static users, added `users.py` which has the expected data of the users used during testing.
* Added a check to see if the app is testing mode or development mode. This is done in `helpers/auth/authentication.py`.
* git checkout to `ft-mock-auth-api-endpoint-for-tests-163971253 ` and go to `helpers/auth/authentication.py` comment out `api_url` and run tests. They should pass without calling the Andela Api.
* Not applicable
* Not applicable
[#163971253](https://www.pivotaltracker.com/n/projects/2154921/stories/163971253)
=> #163971253 Mock Andela Api

api/office/schema.py, helpers/email/email.py, templates/office_success.html
The email sent from the backend should borrow some elements of the front-end UI to make it easier for a user to Identify the source of the email at a glance. 
- Pull this branch
- make the migrations as explained in the [README](https://github.com/andela/mrm_api/blob/develop/Readme.md)
- create a location and within that location create an office.
* mutation for creating an location
```
mutation {
createLocation(name: "location_name", abbreviation: "NRB", country: "Kenya", timeZone: "EAST_AFRICA_TIME", imageUrl:"https://lala.com") {  
location {
name
}
}
}
```
* mutation for creating an office
```
mutation {
createOffice(name: "office_name", locationId: location_id) {
office {
name
locationId
blocks {
id
name
}
}
}
}
```
* initial email from backend
* new email from backend
- Only works …
=> #164312290 Refactor email sent from backend

.coveragerc, alembic/env.py, tests/base.py
The PR enables the use of newly generated alembic files when testing changes to the codebase.
Previously, any changes to alembic files would go unnoticed during testing because tables were generated using sqlalchemy's `.create_all)` method.
This PR includes commands to run migrations during the setup for each test.
The PR also includes a name generator for constraints in tables such as unique and foreign key.
Check the test db for an alembic_version table after running tests.
Before this implementation, there is no such table created.
N/A
[#164163073](https://www.pivotaltracker.com/story/show/164163073)
N/A
=> #164163073 Test that generated alembic files have no errors.

.circleci/config.yml
[#164398414](https://www.pivotaltracker.com/story/show/164398414)
=> #164398414 rename coverage files with commit SHA1

tests/test_events/test_events_ratios.py
The PR fixes a failing test in develop.
The test on database connection is failing due to arguments being passed by the patch wrapper. This PR removes the wrapper from the class level.
Run the `coverage run -m pytest` command
N/A
[#164431237](https://www.pivotaltracker.com/story/show/164431237)
N/A
=> #164431237 Fix failing test in develop

.coveragerc, alembic/env.py, tests/base.py
The PR enables the use of newly generated alembic files when testing changes to the codebase.
Previously, any changes to alembic files would go unnoticed during testing because tables were generated using sqlalchemy's `.create_all)` method.
This PR includes commands to run migrations during the setup for each test.
The PR also includes a name generator for constraints in tables such as unique and foreign key.
Check the test db for an alembic_version table after running tests.
Before this implementation, there is no such table created.
N/A
[#164163073](https://www.pivotaltracker.com/story/show/164163073)
N/A
=> #164163073 (V2) Test that generated alembic files have no errors.

api/office_structure/schema.py, fixtures/office_structure/delete_level_fixtures.py, tests/base.py, tests/test_office_structure/test_delete_level.py
Remove node/level from structure tree
- Currently, when a node is added, it can not be deleted. This PR adds the endpoint for deleting the node
- Pull this branch 
```
mutation{
deleteLevel(id:1){
node{
id
}
}
}
```
You should be able to delete the node.
Please note that this is a task for `v2`.  
[#164266195](https://www.pivotaltracker.com/story/show/164266195)
**if the level doesn't exist**
=> #164266195 Remove node(level) from structure tree

.gitignore, api/room/schema_query.py, fixtures/events/events_ratios_fixtures.py, fixtures/room/daily_room_events_fixture.py, fixtures/room/most_booked_room_least_booked_rooms_fixtures.py, fixtures/room/query_room_fixtures.py, fixtures/room/room_analytics_bookings_count_fixtures.py, fixtures/room/room_analytics_duration_fixtures.py, fixtures/room/room_analytics_least_used_fixtures.py, fixtures/room/room_analytics_most_used_fixtures.py, fixtures/room/room_monthly_meeting_duration_fixtures.py, helpers/calendar/analytics.py, helpers/calendar/analytics_helper.py, helpers/calendar/calendar.py, helpers/calendar/credentials.py, helpers/calendar/events.py, services/room_cancelation/auto_cancel_event.py, tests/test_events/test_events_ratios.py, tests/test_rooms/test_analytics_total_durations.py, tests/test_rooms/test_create_room.py, tests/test_rooms/test_daily_room_events.py, tests/test_rooms/test_most_booked_least_booked.py, tests/test_rooms/test_query_rooms.py, tests/test_rooms/test_room_analytics.py, tests/test_rooms/test_room_analytics_with_no_meetings.py, tests/test_rooms/test_room_calendar_ids_cleanup.py, tests/test_rooms/test_room_occupants.py, tests/test_rooms/test_room_schedule.py, utilities/calendar_ids_cleanup.py, utilities/validator.py
* Mock the Google Calendar API calls for the tests.
*  Backend tests currently make direct calls to the Google Calendar API. Mock these API calls so we only hit the live API on Staging and Production.
* The codebase has been refactored to ensure that the api calls are made in one file `helpers/calendar/credentials.py`
* The tests have been refactored to ensure that the data they use is from the files `events.json` and `calendar_list.json`, and no longer hit the live api.
* git checkout to `ft-mock-calendar-api-163971800 ` and run the tests.
* Not applicable
* Not applicable
[#163971800](https://www.pivotaltracker.com/story/show/163971800)
=> #163971800 (V2) Mock google calendar api for tests

api/room/schema_query.py, helpers/calendar/credentials.py, helpers/remote_rooms/remote_rooms_location.py, tests/test_rooms/test_query_rooms.py
Restrict query remote rooms by location.
When all remote rooms are queried, the result should be displayed only rooms available in the user location.
- Checkout by running `git checkout ft-restrict-query-remote-rooms-by-location-164101018`
- Perform the query below. Remember to provide the desired location access token.
```
query {
allRemoteRooms {
rooms {
calendarId
name
}
}
}
```
- To return all the remote rooms available, use the `returnAll: true` flag:
```
query {
allRemoteRooms(returnAll: true) {
rooms {
calendarId
name
}
}
}
```
The query returns only the rooms in the admin location. 
N/A
[#164101018](https://www.pivotaltracker.com/story/show/164101018)
- #### Query remote rooms by …
=> #164101018 Restrict Query Remote Rooms by Location

api/room/schema_query.py, helpers/calendar/credentials.py, helpers/remote_rooms/remote_rooms_location.py, tests/test_rooms/test_query_rooms.py
Restrict query remote rooms by location.
When all remote rooms are queried, the result should be displayed only rooms available in the user location.
- Checkout by running `git checkout ft-restrict-query-remote-rooms-by-location-v2-164101018`
- Perform the query below. Remember to provide the desired location access token.
```
query {
allRemoteRooms {
rooms {
calendarId
name
}
}
}
```
- To return all the remote rooms available, use the `returnAll: true` flag:
```
query {
allRemoteRooms(returnAll: true) {
rooms {
calendarId
name
}
}
}
```
The query returns only the rooms in the admin location. 
N/A
[#164101018](https://www.pivotaltracker.com/story/show/164101018)
- #### Query remote rooms by …
=> #164101018 (V2) Restrict Query Remote Rooms by Location 

fixtures/room/most_booked_room_least_booked_rooms_fixtures.py, fixtures/room/room_analytics_duration_fixtures.py, fixtures/room/room_analytics_least_used_fixtures.py, helpers/calendar/analytics.py, helpers/calendar/analytics_helper.py, tests/test_rooms/test_room_analytics_with_no_meetings.py
Ignores rooms with invalid Calendar IDs that are causing Analytics to crash
Currently, the backend appears not to return data for certain locations. This is because some rooms in these locations have invalid Calendar IDs. This PR ensures that analytics continues to work with only rooms that have valid Calendar IDs. 
- Checkout the bug fix branch
- Perform the query below to get most booked rooms.
```
{
analyticsForBookedRooms(startDate: "Jan 14 2019", endDate: "Mar 15 2019", limit:10, criteria:"most_booked"){
analytics{
roomName
count
meetings
percentage
roomName
}
}
}
```
N/A
[#164623476](https://www.pivotaltracker.com/story/show/164623476)
N/A
=> #164623476 Ignore rooms with invalid Calendar IDs

api/room/schema.py, fixtures/room/create_room_fixtures.py
The PR ensures addition of location id during room creation.
The location id has now been set to required, that is one cannot create a room without it.
* git checkout to `chore/164462422-set-location-id-required` and run the following mutation:
```
mutation {
createRoom(
name: "Hello", roomType: "Meeting", capacity: 4, floorId:2, officeId:1, locationId:1,
calendarId:"andela.com_2d3237333239383832343333@resource.calendar.google.com",
imageUrl: "https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg") {
room {
name
roomType
locationId
capacity
imageUrl
}
}
}
```
* Check db to ensure the room created has a location id.
N/A …
=> #164462422 Make location_id a required field

api/question/schema.py, fixtures/questions/create_questions_fixtures.py, tests/test_questions/test_create_question.py, utilities/validations.py
Currently, you can create a question with empty fields with just spaces. The PR strips these spaces so you don't create a question with empty fields
Bug (validate question creation)
- Checkout by running `git checkout bg-validate-questions-creation-164361872`
- Perform the mutation below with empty `quetionTitle`:
```
mutation {
createQuestion(questionType:"1", questionTitle:"   ", question:"How would you rate the cleanliness of this room",
startDate: "2019-03-12T14:25:00", endDate: "2019-03-19T14:25:37")
{
question{
id,
questionTitle,
questionType,
question
}
}
}
```
- create Question with all the required:
```
mutation {
createQuestion(questionType:"Ratings", questionTitle:"Room Tablets", …
```
=> #164361872 Validate Questions Creation.

api/room/schema.py, api/room/schema_query.py, fixtures/room/room_analytics_bookings_count_fixtures.py, helpers/calendar/analytics_helper.py, helpers/calendar/ratios_and_utilization.py, tests/test_rooms/test_room_analytics.py, utilities/verify_ids_for_room.py
Fetch Total Booking Count for a Specific Room
Ensure that the user can view the booking count of a single room.
git checkout `ft-room-booking-count-164471444`
run the mutation below to view bookings for a room with id `1`
Daily bookings count
````
query {
bookingsAnalyticsCount(startDate:"Nov 10 2018", endDate:"Nov 12 2018", roomId:1){
roomName
period
bookings
}
}
````
monthly room bookings query
````
query {
bookingsAnalyticsCount(startDate:"Aug 1 2018", endDate:"Nov 1 2018", roomId:4){
roomName
period
bookings
}
}
````
[#164471444](https://www.pivotaltracker.com/story/show/164471444)
Daily bookings count
Monthly bookings count
=> #164471444 Fetch Total Booking Count for a Specific Room

api/room/schema_query.py, helpers/calendar/analytics_helper.py, helpers/calendar/events.py
Query the status of the daily room events
A user should be able to query the status of daily room events and know what events have been canceled and what events are active
- Checkout by running `git checkout ft-query-status-of-daily-room-events-164673176`
- Perform the query below to get all locations.
```
query{
analyticsForDailyRoomEvents(startDate:"jan 10 2019", endDate:"jan 10 2019"){
day
events{
state
checkedIn
cancelled
eventSummary
startTime
endTime
roomName
noOfParticipants
eventId
}
}
}
```
N/A
[#164673176](https://www.pivotaltracker.com/story/show/164673176)
=> #164673176 Query status of daily room events

api/room/schema_query.py, fixtures/room/daily_room_events_fixture.py, tests/test_rooms/test_daily_room_events.py
Paginate analytics for daily room events
Currently, when querying the analytics for daily room events, the result isn't paginated. This PR adds functionality to paginate the results when both the `page` number and items `perPage` are provided.
- Checkout by running `git checkout ft-paginate-room-events-164823820`
- Perform the query below. This will return all the rooms without pagination 
```
query{
analyticsForDailyRoomEvents(startDate:"jan 10 2019", endDate:"feb 10 2019"){
day
events {
noOfParticipants,
eventSummary,
startTime,
endTime,
roomName,
eventId
}
}
}
}
```
- query analytics for daily room events with pagination.
```
query{ …
```
=> #164823820 (v2) Paginate room events

api/room/schema_query.py
Fix a bug that returns the most booked rooms when querying for the least booked rooms
- A user should be able to query for the least booked rooms and in return get them from the least booked to the most booked.
- Clone the branch and follow the setup steps in the README.
- Checkout to the branch by using the command `git checkout bg-least-booked-rooms-164824376`
- Start the server and navigate to the right url.
- Make a query to get analytics for most booked rooms using the query below
- You can set a `limit` on the number of rooms you would like displayed. This should be an `int`
- You can also set a `criteria` on what you want to query. Use `most_booked` or `least_booked` as an argument. Omiting this argument will display `most_booked` by default.
```
{ …
```
=> #164824376 Fix least booked rooms bug v2

api/response/schema_query.py, fixtures/response/room_response_fixture.py, helpers/response/query_response.py, tests/test_response/test_room_response.py, utilities/validations.py
Enable admin to query feedback responses based on date range
- Currently, when querying responses, one can not query responses by date. This PR allows an admin to query responses by date range. 
- The query can also be run with a `room`  as shown below
- The code has been refactored to cater for both `date range` and `count range` since the functionality is almost similar
- Pull this branch `ft-query-responses-with-data-range-164167409`
```
query{
allRoomResponses(startDate: "2019 feb 20", endDate: "2019 feb 25" ){
responses{
totalResponses
roomName
response{
responseId
missingItems
}
}
}
}
```
or 
```
query{
allRoomResponses(startDate: "2019 feb 20",  endDate: "2019 feb 25", room: "Entebbe" ){
responses{
totalResponses
roomName
response{
responseId
missingItems …
```
=> #164167409 Enable admin to query feedback responses based on date range

api/room/schema_query.py
Fix a bug that returns the most booked rooms when querying for the least booked rooms
- A user should be able to query for the least booked rooms and in return get them from the least booked to the most booked.
- Clone the branch and follow the setup steps in the README.
- Checkout to the branch by using the command `git checkout bg-least-booked-rooms-v1-164824376`
- Start the server and navigate to the right url.
- Make a query to get analytics for most booked rooms using the query below
- You can set a `limit` on the number of rooms you would like displayed. This should be an `int`
- You can also set a `criteria` on what you want to query. Use `most_booked` or `least_booked` as an argument. Omiting this argument will display `most_booked` by default.
```
{ …
```
=> #164824376 Fix least booked rooms bug (v1)

api/room/schema_query.py, helpers/calendar/analytics_helper.py, helpers/calendar/events.py
Add check-in time and meeting end time to Query the status of the daily room events
A user should be able to query the status of daily room events and know what time a user checks in and ends a meeting.
- Clone the repository and carry out the steps laid out [here](https://github.com/andela/mrm_api).
- Checkout by running `git checkout ft-query-checkin-endmeeting-time-for-event-165056357`
- Perform the query below to get the status of the room events (checkin time and meeting end time).
```
query
{
analyticsForDailyRoomEvents(startDate: "Jan 1 2019", endDate: "Apr 1 2019") {
day
events {
state
eventSummary
startTime
endTime
cancelled
roomName
noOfParticipants
checkInTime
meetingEndTime
}
}
}
}
```
N/A
[#165056357](https://www.pivotaltracker.com/story/show/165056357)
=> #165056357 Add check-in time and meeting end time to daily room events Query

api/room/schema_query.py, fixtures/room/daily_room_events_fixture.py, tests/test_rooms/test_daily_room_events.py
Paginate analytics for daily room events
Currently, when querying the analytics for daily room events, the result isn't paginated. This PR adds functionality to paginate the results when both the `page` number and items `perPage` are provided.
- Checkout by running `git checkout ft-paginate-room-events-v1-164823820`
- Perform the query below. This will return all the rooms without pagination 
```
query{
analyticsForDailyRoomEvents(startDate:"jan 10 2019", endDate:"feb 10 2019"){
day
events {
noOfParticipants,
eventSummary,
startTime,
endTime,
roomName,
eventId
}
}
}
}
```
- query analytics for daily room events with pagination.
```
query{ …
```
=> #164823820 (v1) Paginate room events

api/events/schema.py, fixtures/events/event_checkin_fixtures.py
Add a checkintime to events checkin mutation 
-Feature (Add checkintime to eventscheckin mutation)
- Pull this branch `ft-checkin-time-mutation-164890997`
- Run the `eventCheckin` mutation with 
```
mutation {
eventCheckin(
calendarId:"andela.com_3836323338323230343935@resource.calendar.google.com",
eventId:"6i9bhvfbbjphflqel1prhbdh1g_20180710T150000Z", 
eventTitle:"Google<>Andela<>Udacity Meeting", numberOfParticipants: 11,
startTime:"2018-07-10T08:00:00-07:00",
endTime:"2018-07-10T09:00:00-07:00",
checkInTime:"2018-07-10T08:00:00-07:00"){
event{
eventId
roomId
checkedIn
cancelled
checkInTime
room{
id
name
calendarId
}
}
}
}
```
- You should be able to have checkin time when you checkin
- Run the version 2 data dump
- Make sure the event exists in the database
- Make sure the event is …
=> #164890997 Add check-in-time to events checkin mutation

api/room/schema_query.py, fixtures/room/filter_room_fixtures.py, tests/test_rooms/test_room_filter.py
Adds functionality to filter rooms by tag
**Description of the task to be completed?**
- A user should be able to get rooms that have a particular tag
- use the query below to filter rooms by tag
```
query {
filterRoomsByTag(tagId:1){
id
name
}
}
```
**Screenshots if any**
N/A
[#165014699](https://www.pivotaltracker.com/story/show/165014699)
Checklist:
=> #165014699 Filter rooms by tag

api/room/schema.py, api/room/schema_query.py, fixtures/events/events_ratios_fixtures.py, helpers/calendar/analytics_helper.py, helpers/calendar/ratios_and_utilization.py, tests/test_events/test_events_ratios.py
Enable admins to view count and auto-cancellation for a single room
- Extend get_per_room function to return single room analytics
- Add tests to cover feature
2. Cd into the cloned repo and checkout to this
3. Git pull branch `ft-cancellation-analytics-single-room-164471450-v1`
4. Run migrations
5. Run the query
```
query{
analyticsRatiosPerRoom(startDate:"Mar 1 2019", endDate:"Mar 27 2019", roomId:1){ 
ratio{
roomName
bookings
checkins
cancellations
appBookings
}
}
} 
```
`Getting all rooms`
`Getting analytics for a single room rooms`
[#164471450](https://www.pivotaltracker.com/story/show/164471450)
=> #164471450 Analytics for auto-cancellation of a single meeting room

api/events/schema.py, fixtures/events/end_event_fixtures.py, helpers/calendar/events.py, tests/test_events/test_end_event.py
Add a mutation to end meeting
As a user I want to end a meeting from the mobile app and have this updated in the event table so that I can save the time when the meeting actually ended
- git pull and checkout branch ft-end-meeting-mutation-164890924
- Ensure you have a checked-in event
- run the mutation below
```
mutation {
endEvent(calendarId:"andela.com_353633323439323830@resource.calendar.google.com",
eventId:"3f85pi6jgpc1qslnp312k3k4fl", startTime:"2018-04-10T01:00:00-07:00",
endTime:"2018-04-10T03:00:00-07:00", meetingEndTime:"2018-02-07T04:15:00-08:00")
{
event{
eventId
eventTitle
checkedIn
cancelled
meetingEndTime
room{
id
name
calendarId
}
}
}
}
```
[#164890924](https://www.pivotaltracker.com/story/show/164890924)
=> #164890924 Add mutation to end meeting

api/room/schema.py, api/room/schema_query.py, fixtures/room/room_analytics_bookings_count_fixtures.py, helpers/calendar/analytics_helper.py, helpers/calendar/ratios_and_utilization.py, tests/test_rooms/test_room_analytics.py, utilities/verify_ids_for_room.py
Fetch Total Booking Count for a Specific Room
Ensure that the user can view the booking count of a single room.
git checkout `ft-room-booking-count-164471444`
run the mutation below to view bookings for a room with id `1`
Daily bookings count
````
query {
bookingsAnalyticsCount(startDate:"Nov 10 2018", endDate:"Nov 12 2018", roomId:1){
roomName
period
bookings
}
}
````
monthly room bookings query
````
query {
bookingsAnalyticsCount(startDate:"Aug 1 2018", endDate:"Nov 1 2018", roomId:4){
roomName
period
bookings
}
}
````
[#164471444](https://www.pivotaltracker.com/story/show/164471444)
Daily bookings count
Monthly bookings count
=> #164471444 Fetch Total Booking Count for a Specific Room (V2) 

api/office_structure/models.py, api/office_structure/schema.py, fixtures/office_structure/create_node_fixtures.py, tests/base.py, tests/test_office_structure/test_add_node.py, utilities/validator.py
Adds the tag_id argument to the addNode endpoint
When an admin is creating a new node they can add an optional argument tag_id.
- Checkout by running `git checkout story/164457514-add-tagid-to-addnode-endpoint`
- Perform the mutation below to create a new tag.
```
mutation {
createTag (name: "BlockA", color: "blue", description: "Block") {
tag {
id,
name,
color,
description
}
}
}
```
- Perform this mutation to add the tag_id from the created tag.
```
mutation{
createNode(name:"Block", tagId:1){
node{
id
name
level
left
right
}
}
}
```
N/A
[#164457514](https://www.pivotaltracker.com/story/show/164457514)
- #### Mutation to add the tag_id
- #### The added tag_id into the database
=> #164457514 Add tag id to addNode endpoint

api/events/schema.py, fixtures/events/end_event_fixtures.py, helpers/calendar/events.py, tests/test_events/test_end_event.py
Add a mutation to end meeting. This PR updates `develop` with the changes introduced to `v2` [here](https://github.com/andela/mrm_api/pull/341).
As a user I want to end a meeting from the mobile app and have this updated in the event table so that I can save the time when the meeting actually ended
- git pull and checkout branch ft-end-meeting-mutation-v1-164890924
- Ensure you have a checked-in event
- run the mutation below
```
mutation {
endEvent(calendarId:"andela.com_353633323439323830@resource.calendar.google.com",
eventId:"3f85pi6jgpc1qslnp312k3k4fl", startTime:"2018-04-10T01:00:00-07:00",
endTime:"2018-04-10T03:00:00-07:00", meetingEndTime:"2018-02-07T04:15:00-08:00")
{
event{
eventId
eventTitle
checkedIn
cancelled
meetingEndTime
room{
id
name
calendarId
}
}
}
} …
```
=> #164890924 Add mutation to end meeting v1

api/response/schema_query.py, fixtures/response/room_response_fixture.py, helpers/response/query_response.py, tests/test_response/test_room_response.py, utilities/validations.py
Enable admin to query feedback responses based on date range
- Currently, when querying responses, one can not query responses by date. This PR allows an admin to query responses by date range. 
- The query can also be run with a `room`  as shown below
- The code has been refactored to cater for both `date range` and `count range` since the functionality is almost similar
- Pull this branch `ft-query-responses-with-data-range-164167409`
```
query{
allRoomResponses(startDate: "2019 feb 20", endDate: "2019 feb 25" ){
responses{
totalResponses
roomName
response{
responseId
missingItems
}
}
}
}
```
or 
```
query{
allRoomResponses(startDate: "2019 feb 20",  endDate: "2019 feb 25", room: "Entebbe" ){
responses{
totalResponses
roomName
response{
responseId
missingItems …
```
=> #164167409 Enable admin to query feedback responses based on date range (V2)

api/structure/schema.py, fixtures/structure/structures_fixtures.py, helpers/auth/admin_roles.py, tests/base.py, tests/test_structure/test_all_structures.py, tests/test_structure/test_structure.py
Restrict office structure query according to location
Currently, admin can query all of the levels regardless of their locations, this PR makes sure an admin should query office structures(levels) that only belong to their locations
- git pull and checkout branch bg-query-structures-bylocation-165240715
- Run the following mutations
```
{
allStructures {
structureId
level
name
parentId
tag
locationId
position
}
}
```
```
{
structureByStructureId(structureId: "b05fc5f2-b4aa-4f48-a8fb-30bdcc3fc968")
{
name
level
tag
}
}
```
[#165240715](https://www.pivotaltracker.com/story/show/165240715)
* Make sure to create office structures using the structure fixture
* Try playing around the location_id in postico
=> #165240715 Restrict office structures query by location

helpers/calendar/analytics.py
Currently, When querying booked rooms when there are no events in the database,  the query returns a division error as shown below. This PR fixes this error by allowing the query to return an empty list instead of the ambiguous error.
```
{
"errors": [
{
"message": "division by zero",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"analyticsForBookedRooms"
]
}
],
"data": {
"analyticsForBookedRooms": null
}
}
```
- This is a bug fix
- Pull this branch `ch-fix-analytics-for-booked-rooms-165355134`
- Ensure that the event database is empty
- Run the `analyticsForBookedRooms` query with 
```
query{
analyticsForBookedRooms(startDate:"Jan 20 2019", endDate:"Feb 20 2019"){
analytics{
roomName
}
}
}
```
[#65355134](https://www.pivotaltracker.com/story/show/165355134)
=> #165355134 Fix analytics for booked rooms

api/room/schema.py, app.py
Adds notifications endpoint to redirect to specified URL
A notifications endpoint should accept both GET and POST endpoints and redirect to the specified URL
- Checkout by running `gco bg-add-notification-endpoint-165412771`
- Start the server and navigate to `/notifications`
[#165412771](https://www.pivotaltracker.com/story/show/165412771)
=> #165412771 Create notification endpoint to redirect

api/room/schema.py, api/room/schema_query.py, fixtures/events/events_ratios_fixtures.py, helpers/calendar/ratios_and_utilization.py, tests/test_events/test_events_ratios.py
Enable admins to view count and auto-cancellation for a single room
- Extend get_per_room function to return single room analytics
- Add tests to cover feature
2. Cd into the cloned repo and checkout to this
3. Git pull branch `ft-cancellation-analytics-single-room-164471450-v2`
4. Run migrations
5. Run the query
```
query{
analyticsRatiosPerRoom(startDate:"Mar 1 2019", endDate:"Mar 27 2019", roomId:1){ 
ratio{
roomName
bookings
checkins
cancellations
appBookings
}
}
} 
```
`Getting all rooms`
`Getting analytics for a single room`
[#164471450](https://www.pivotaltracker.com/story/show/164471450)
=> #164471450 Analytics for auto-cancellation of a single meeting room - v2

helpers/calendar/events.py
Currently, When running a mutation to sync event table in the local database with events data from the Google calendar API,  the mutation crushes and returns a key error as shown below. This PR fixes this error by allowing the mutation to successfully populate the events table.
```
{
"errors": [
{
"message": "'dateTime'",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"syncEventData"
]
}
],
"data": {
"syncEventData": null
}
}
```
- This is a bug fix
- Pull this branch `bg-fix-error-on-populating-events-table-165570624`
- Ensure that the event database is empty
- Run the mutation `syncEventData`  as shown below 
```
mutation{
syncEventData{
message
}
}
```
[#165570624](https://www.pivotaltracker.com/story/show/165570624)
=> #165570624 Fix the key error on syncEventdata mutation

requirements.txt
Fixes HTTPS Conn errors on notifications endpoint.
Add two libraries that help with HTTPs handshaking
Try and access the notifications endpoint (`<BACKEND-API-URL>/notifications`), it should not be timing out anymore
N/A
[#165595771](https://www.pivotaltracker.com/story/show/165595771)
=> #165595771 Fix HTTPS conn errors on notifications endpoint

api/room/schema_query.py, fixtures/room/filter_room_fixtures.py, helpers/room_filter/room_filter.py, tests/base.py, tests/test_rooms/test_room_filter.py
Adds a `roomLabels` argument to `allRooms` query that filters rooms by wings and floors
When a user provides the argument `roomLabels` to the `allRooms` query the query returns all rooms that have that label. One can also provide comma separated labels to perform a deeper filter and only rooms that contain the provided labels will be returned
- Checkout by running `gco ft-filter-meeting-rooms-by-wings-and-floors-165210376`
- Perform the mutation below to query rooms with the specified labels.
```
{
allRooms(roomLabels:"Block A, Wing B"){
rooms{
id
name
roomLabels
}
}
}
```
You must create rooms with the room labels you want to query with, otherwise, no rooms will be returned. …
=> #165210376 Filter meeting rooms by wings and floors

api/room_resource/schema.py, fixtures/room_resource/get_room_resource_fixtures.py, tests/test_room_resource/test_get_resource_list.py
Adds query for getting all resources assigned to a given room
As an admin, it should be possible to get all the resources assigned to a given room by suppliying the query with the desired `roomId`
- Checkout by running `git checkout ft-query-all-resources-165377719`
- Follow instructions to assign a resource to a room from #353 
- Run the following query as an **admin** to fetch all the resources assigned to a given `roomId`
```
{
getResourcesByRoomId(roomId:1){
roomResources{
name
id
quantity
}
}
}
```
N/A
[#165377719](https://www.pivotaltracker.com/story/show/165377719)
- #### Existing room resources:
- #### Non existing `roomId`:
- #### Get room resources by a `non admin`:
=> #165377719 Query All Room Resources by RoomId

api/room/schema.py, fixtures/helpers/decorators_fixtures.py, fixtures/room/create_room_fixtures.py, fixtures/structure/create_structure_fixtures.py, tests/test_rooms/test_create_room.py, utilities/validations.py
- Validates room labels such that it only allows a list of strings
- Prevents Admin from creating room labels for a structure that does not exist.
**Description of the Task to be completed**
- At the moment, when the Admin is creating a room. They can be able to add a list of dictionaries.
- The Admin is also able to create a room in a structure that does not exist. The bug fix handles this issue.
- git pull the branch `bg-labels-accept-strings-165443496`
- Run the application
- Checkout to the branch and run the following mutation
```mutation {
createRoom(
name: "mongoliae",
roomType: "Meeting",
capacity: 4,
locationId: 1,
calendarId: "andela.com_2d3437383637373630343336@resource.calendar.google.com",
imageUrl: …
```
=> #165443496 Room labels should only accept a list of strings

api/room_resource/schema.py, fixtures/room_resource/update_assigned_resource.py, tests/test_room_resource/test_update_assigned_resource.py
Update an assigned room resource
Currently, one can assign a resource to a room using an association object, this PR makes it possible to update the quantity on the association object
- git pull and checkout to the branch ft-update-assigned-resource-165014764
- Run the following mutation
```
mutation{
updateAssignedResource(roomId:1, resourceId:1, quantity: 5){
roomResource{
roomId
resourceId
quantity
}
}
}
```
[165014764](https://www.pivotaltracker.com/story/show/165014764)
* Assign a resource first
* Ensure the resource of id one is assigned to room one to use the above mutation
=> #165014764 Update an assigned room resource

api/room/models.py, api/room_resource/schema.py, fixtures/room_resource/get_rooms_with_resource_fixtures.py, tests/test_room_resource/test_query_rooms_with_resource.py
- It allows an admin to query for the rooms that contain a particular resource
- Create a query that allows an admin to get the rooms that a resource can be found after providing the `resourceId`
-  Follow the instructions [here](ur) to assign a resource to a room. 
- Run the query below with a valid `resourceId` and you will get the list of rooms with that resource provided you are an admin
```
query {
roomsContainingResource(resourceId: 1) {
room {
name
capacity
}
}
}
```
[#165557236](https://www.pivotaltracker.com/story/show/165557236)
=>  #165557236 Allow admin get rooms that contain a resource

api/events/schema.py, api/location/schema.py, api/office/schema.py, api/user/schema.py, fixtures/events/event_checkin_fixtures.py, helpers/calendar/credentials.py, helpers/email/email.py, services/room_cancelation/auto_cancel_event.py, templates/event_cancellation.html, tests/test_events/test_event_checkin.py
Enable a user to receive an email notification when a meeting is rejected.
The following are scenarios where we will send email notifications when a room rejects the booking of an event:
- When a user misses to check-in within 10 minutes after the meeting has started.
- When a user misses to check-in for 3 consecutive meetings. All future bookings to the specific room will be rejected. 
- git pull and checkout branch ft-cancelled-event-notification-v2-165222721
- run the cancelEvent mutation below
```
mutation {
cancelEvent(
calendarId:"andela.com_38393338303730373538@resource.calendar.google.com",
eventId:"041t6mhogr8cq7i8vvr2h36d9p", eventTitle:"First LFA On-Boarding", numberOfParticipants: 13,
startTime:"2018-08-14T06:00:00-07:00",
endTime:"2018-08-14T07:00:00-07:00") …
```
=> #165222721 Send email notification on event rejection

templates/event_cancellation.html
Ensure the email text fits with the container width
Currently, when the email text for event rejection notification is long it tends to overflow the html container. This PR ensures the content fits the container.
- git pull and checkout branch bg-fix-event-notification-template-16582252
- run the cancelEvent mutation.
[#165222721](https://www.pivotaltracker.com/story/show/165822522)
=> #165822522 Fix event email notification template

api/devices/schema.py, fixtures/devices/devices_fixtures.py, fixtures/user/user_fixture.py, tests/base.py, tests/test_devices/test_all_devices.py
- Currently, there is an existing query that fetches all devices. The aim of this PR is to refactor the query to get the devices based on the location of the user making the request.
- Refactor the query to return data based on user location
- Ensure existing tests pass
- Pull this branch `ft-query-devices-per-location-165592500`
- Run a new migration to migrate to the V2 database
- Create devices using `createDevice` mutation. If you need help running these mutations, check out the documentation for the [mrm endpoints](http://localhost:8000/mrm)
- After creating devices, you can run the following query 
```
{
allDevices {
id
lastSeen
dateAdded
name
location
}
}
```
n/a
[#165592500](https://www.pivotaltracker.com/story/show/165592500)
=> #165592500 Restricting querying devices by location

api/room_resource/schema.py, fixtures/room_resource/delete_assigned_resource_fixtures.py, tests/test_room_resource/test_delete_assigned_resource.py
Enable admins to delete a resource assigned to a room
- Implement logic to aid feature functionality
- Write tests for the feature
1. Git pull branch `ft-delete-assigned-resource-165535238`
2. Follow instructions to assign a resource to a room from [#353](https://github.com/andela/mrm_api/pull/353)
2. Run the mutation below to delete the assigned resource
```
mutation {
deleteAssignedResource(resourceId: 1, roomId: 1) {
roomResource {
roomId
resourceId
quantity
}
}
}
```
* On Success
* On Failure 
[#165535238](https://www.pivotaltracker.com/story/show/165535238)
=> #165535238 Delete assigned room resource

docker/dev/start_gunicorn.sh, docker/prod/start_gunicorn.sh
Additional configuration for gunicorn to limit the worker connections to 1000 and introduce a timeout of 30 seconds.
- Added a gunicorn worker connection limit of 1000
- Added a gunicorn timeout of 30 seconds
N/A
[#166150047](https://www.pivotaltracker.com/story/show/166150047)
=> #166150047 Limit worker connections and timeout

api/analytics/all_analytics_query.py, fixtures/analytics/query_all_analytics_fixtures.py, helpers/calendar/all_analytics_helper.py, helpers/calendar/analytics_helper.py, schema.py, tests/test_analytics/test_all_analytics_query.py, utilities/utility.py
Create a query for the analytics page
Currently, the analytics page runs at least six queries, this PR makes one query to be used by the analytics page to optimise the response time.
- git pull and checkout to the branch ft-refactor-analytics-queries-166147378
```
query {
allAnalytics(startDate: "May 1 2019", endDate: "May 22 2020"){
bookings
analytics{
roomName
cancellations
numberOfMeetings
checkins
percentageShare
appBookings
bookingsCount{
period
bookings
}
events{
durationInMinutes
}
}
}
}
```
[166147378](https://www.pivotaltracker.com/story/show/166147378)
None
=> #166147378 Consolidate analytics queries into one

api/user/schema.py, fixtures/user/user_fixture.py, fixtures/user_role/user_role_fixtures.py, helpers/email/email.py, templates/admin_invite.html, tests/base.py, tests/test_user/test_change_user_role.py, tests/test_user_roles/test_query_user_role.py
Currently, there's an existing implementation for changing a user's role. The aim of this PR is to check when a user's role is being changed to admin and send an email notification to that user.
- Send email notification to newly added admin
- Ensure existing tests pass.
- Pull this branch ft-admin-receive-notification-when-added-165528858
- Make sure your application containers are running
```
mutation {
changeUserRole(email: "email@email.com", roleId: 2) {
user {
name
roles{
role
}
}
}
}
```
- For the `email` field in the mutation, make use of an existing valid email address in your User model.
- For the `roleId` field in the mutation, let the id being passed tally with the id of the role admin in your Role model. …
=> #165528858 User should receive notification when added as an admin

api/analytics/all_analytics_query.py, fixtures/analytics/query_all_analytics_fixtures.py, helpers/calendar/all_analytics_helper.py
Fix the bookings count, percentage share tally, auto cancellations and app_bookings logic.
Currently, the bookings count for different periods does not tally to the total number of meetings in a room, percentage share is off, the duration in minutes is returned for every event and overall percentages have also been added.
The app_bookings and auto_cancellations logic has also been added.
- git pull and checkout to the branch bg-fix-bookings-and-percentages-166210077
```
query {
allAnalytics(startDate: "Jan 11 2018", endDate: "may 11 2019"){
autoCancellationsPercentage
bookings
analytics{
roomName
cancellations
numberOfBookings
checkins …
```
=> #166210077 Fix bookings count and percentage share

api/room/schema.py, fixtures/room/room_update_fixtures.py, tests/test_rooms/test_update_room.py
Enable room update without providing the structure id
Currently, when updating the room, the mutation requires the structure id to always be provided and 
goes on to run the structure id validation which returns structure does not exist when there is no id, this
PR makes sure the validation method is only called when the structure id is in the keyword arguments 
(kwargs)
- git pull and checkout to the branch bg-room-update-165939988
- Run the following mutation to update a room
```
mutation{
updateRoom(roomId: 5, name: "Jinja", capacity: 8,
roomTags: [1]){
room{
name
capacity
roomType
}
}
}
```
[165939988](https://www.pivotaltracker.com/story/show/165939988)
None
Without structure_id
With structure_id
=> #165939988 Enable room update without structure id

api/response/schema.py, fixtures/response/user_response_check.py, tests/test_response/test_user_response.py
- It helps to paginate the responses received while running the `getRoomResponse` query.
- Modified the `getRoomResponse` resolver function to paginate responses instead of sending them all.
- Pull this branch ft-paginate-room-responses-166034806
- Make sure your application containers are running
```
query {
getRoomResponse (
roomId: 1,
page: 1,
perPage: 2
) {
responses {
totalResponses
response {
rating
missingItems
suggestion
}
}
hasNext
hasPrevious
pages
}
}
```
- The `hasNext`, `hasPrevious` and `pages` fields are pagination metadata that'll eventually be used on the frontend.
- `Responses` returns an array of responses which the amount has been specified in the `perPage` query.
- The `perPage` query param is the number of responses to be returned while the …
=> #166034806 Paginate room responses on getRoomResponse

api/room/schema.py
Add the delete room push notification endpoint to the delete room mutation.
Once a room is deleted from the converge database we want to stop the room from listening for push notifications and delete it from the Redis database.
- git pull the branch `ft-delete-room-functionality-165849371`
- Ensure you have the `MRM_PUSH_URL` in the `.env`
- Ensure you have [setup](https://github.com/andela/mrm_push) mrm_push
- Call the `refresh` endpoint to add rooms to the database http://127.0.0.1:5000/refresh
- Run the deleteRoom mutation below:
```
mutation{
deleteRoom(roomId:1){
room{
name
capacity
roomType
}
}
}
```
Testing this functionality involves ensuring that the two applications have been set and are working locally.
[#165849371](https://www.pivotaltracker.com/story/show/165849371)
=> #165849371 Add delete room push notification feature

api/devices/schema.py, fixtures/devices/devices_fixtures.py, tests/test_devices/test_specific_device.py
Enables a user to fetch a specific device using the device Id
- add a query to fetch device by device ID
- test query to fetch specific device
3. checkout to branch `ft-query-device-by-deviceID-166051871`
3. on insomnia send query
```
{
specificDevice(deviceId: 1) {
name
deviceType
location
room {
name
}
}
}
```
[#166051871](https://www.pivotaltracker.com/story/show/166051871)
=> #166051871 Query device by device ID

api/response/schema.py, helpers/response/create_response.py, tests/test_response/test_user_response.py
It ensures that the createResponse mutation works as described.
We should ensure that it should handle all the validations, and return a response object created instead of an error or blank response when performing mutations under the following conditions:
- Run create response mutation with all the required fields
- Run create response mutation with only the missing items being reported
- Run create response mutation with response type which is different from the question type
- Run create response mutation when trying to respond to a question whose start date is yet to commence.
- Ensure you have resources in your database.
- Ensure that one room has some resources in it.
- Ensure you have question types of `check`, `input` and `rate` to respond to. 
- The mutations for the responses …
=> #165903102 Fix createResponse mutation

api/events/schema.py, fixtures/events/events_query_fixtures.py, schema.py, tests/test_events/test_query_all_events.py
Create a query all events endpoint
Enable users to query all active events
- git pull and checkout to the branch ft-query-room-events-166283692
```
query{
allEvents(startDate: "jul 26 2018", endDate: "jul 27 2019"){
id
room{
name
}
eventTitle
}
}
```
[166283692](https://www.pivotaltracker.com/story/show/166283692)
None
=> #166283692 Query all events

api/response/schema_query.py, fixtures/response/room_response_fixture.py, helpers/response/query_response.py, tests/base.py
- The aim of this PR is to refactor the `allRoomResponses` query to allow filtering responses by date range
- Fix query by date range
- Refactor endpoint to reduce complexity
- Remove unnecessary duplication
- Pull this branch `bg-fix-query-all-responses-by-date-range-165903538`
- Ensure that you have a number of responses in your database
- Run the query below for filtering by date range only
```
query{
allRoomResponses(startDate: "jan 1 2019",
endDate: "mar 10 2019"){
responses{
totalResponses
roomName
response{
responseId
}
}
}
} 
```
For filtering with additional parameters run the query below
```
query{
allRoomResponses(startDate:"may 1 2019", endDate:"may 29 2019" ,upperLimitCount:5, lowerLimitCount:1, page:1, perPage:1){
responses{         
totalResponses
roomName
roomId
response{ …
```
=> #165903538 Fix all reponses query to filter by date range

api/events/schema.py, helpers/calendar/events.py
This PR ensures bookings made from the app and events that are auto-canceled are indicated.
Currently, there is no way to differentiate between events that were auto-canceled and those that were checked-in and later ended. Also, events that are booked using the app and those that were booked using the google calendar cannot be differentiated. This PR ensures these issues are resolved.
- You might need to clear your events model to enable you to see the new events after sync
- Change the calendar id of one of your rooms to `andela.com_3131313630383336383038@resource.calendar.google.com` as this calendar has bookings with the mobile app. Make sure the `next_sync_token_column` is null
- Set all rooms to `archived` except the one you just changed the calendarId
- Sync your database with the …
=> #166208042 Indicate auto-cancellations and app-bookings

fixtures/analytics/query_all_analytics_fixtures.py, helpers/calendar/all_analytics_helper.py, helpers/calendar/analytics_helper.py
Fix the bookings count to display bookings for a today's date and fix failing tests.
Currently, the bookings count will return an empty list when you query for today's bookings. It should return the booking date and the number of bookings for that day. 
This PR also adds a `__init__.py` file in the `test_analytics` folder.
- git pull and checkout to the branch bg-fix-failing-tests-166245190
```
query {
allAnalytics(startDate: "may 27 2019", endDate: "may 27 2019"){
autoCancellationsPercentage
bookings
analytics{
roomName
cancellations
numberOfBookings
checkins
bookingsPercentageShare
appBookings …
```
=> #166245190 Fix booking count and failing tests

api/events/schema.py, fixtures/events/events_query_fixtures.py, helpers/calendar/analytics_helper.py
Fix the events query
At the moment, the events query returns all the events, this PR returns day and the events that took place on that day
- git pull and checkout to the branch bg-fix-events-query-166332095
-  run application
```
query{
allEvents(startDate: "may 20 2019", endDate: "may 29  2019"){
day
events{
id
roomId
room{
name
}
}
}
}
```
[166332095](https://www.pivotaltracker.com/story/show/166332095)
None
=> #166332095 Add day of event to events query

api/response/schema_query.py, helpers/response/query_response.py
modifies the  `allRoomResponses` query  to return only rooms with responses
- modify get_all_responses method in `api/response/schema_query.py `
- modify validate_responses_by_room method in `helpers/response/query_response.py`
3. checkout to branch `ch-modify-getAllResponses-166080260`
3. on insomnia send query
```
{
allRoomResponses {
responses {
roomId
roomName
totalResponses
response {
responseId
resolved
}
}
}
}
```
The `allRoomResponses` query used to return all rooms regardless of whether they had a response or not. The query had to be modified to return only rooms with responses
[#166080260](https://www.pivotaltracker.com/story/show/166080260)
=> #166080260 modify getAllResponses to return only rooms with responses

api/events/schema.py, helpers/calendar/events.py, tests/test_events/test_query_all_events.py
-This PR is to get daily events based on the location of the user making the request.
- Refactor the query to return data based on user location
- Ensure existing tests pass
- Pull this branch `restrict-query-events-by-location-166374529`
- Add rooms from various locations and run sync data mutation to sync all events
- Run the following query 
```
query{
allEvents(startDate: "Mar 28 2019", endDate: "Apr 28 2019"){
day
events{
eventId
eventTitle
}
}
}
```
n/a
[#166374529](https://www.pivotaltracker.com/story/show/166374529)
=> #166374529 Restrict event query by location

api/structure/schema.py
Fix the office structures query to return active structures only
When the office structures query was worked on, the state column was not present and it queries all structures regardless of the state, this PR makes sure we return active structures only
- git pull and checkout to the branch 
```
query{
allStructures{
id
state
}
}
```
[166496472](https://www.pivotaltracker.com/story/show/166496472)
None
N/A
=> #166496472 Fix office structures query

fixtures/room/filter_room_fixtures.py, helpers/auth/authentication.py, helpers/room_filter/room_filter.py, tests/test_rooms/test_query_rooms.py, tests/test_rooms/test_room_filter.py
Fix the room filter to ensure that you can filter for rooms using room labels.
Currently, when running the allRooms query using the `location` and `room label`, it will only filter based on location. Filtering on `room label` alone returns rooms with all the room labels specified. This PR seeks to fix this to ensure that you can query for `room label`. The location will automatically be fetched from the user's token since we only want users to filter based off a user's location. In the event that a user does not provide a token, we will return a list of all rooms available. We also fix fetching a resource by fixing the logic that checks for room resources in a room rather than resources in the database.
- git pull and checkout to the branch bg-fix-room-filters-166377619 …
=> #166377619 Fix filter on rooms using room labels

api/events/schema.py, fixtures/events/events_query_fixtures.py, tests/test_events/test_query_all_events.py
With this PR, we can query for paginated daily room events
Currently, the query for daily room events is not paginated. We want to paginate this query.
- Run the following query for paginated daily room events
```
query{
allEvents(startDate: "Mar 28 2019", endDate: "Mar 29 2019", page:1, perPage: 1){
day
events {
eventTitle
}
}
hasNext
hasPrevious
pages
queryTotal
}
}
```
[166323569](https://www.pivotaltracker.com/story/show/166323569)
None
=> #166323569 Paginate daily room events

api/structure/schema.py, fixtures/structure/update_structure_fixtures.py, tests/test_structure/test_update_structure.py
Update an office structure
This PR gives a user with admin privileges the ability to update a given office structure 
- git pull and checkout to the branch ft-update-office-structure-165931398
- Run the following mutation
```
mutation {
updateOfficeStructure(structureId: "b05fc5f2-b4aa-4f48-a8fb-30bdcc3fc968", name:"St.Catherine's", level:3, parentTitle:"parent 5", tag:"offices", position:4, locationId:1, parentId:"2") {
structure {
structureId
name
level
parentId
parentTitle
tag
position
locationId
}
}
}
```
[165931398](https://www.pivotaltracker.com/story/show/165931398)
* Create an office structure
* Ensure the structure id generated is the same one used for the mutation above
=> #165931398 Update  office structures

api/devices/schema.py, fixtures/devices/devices_fixtures.py, tests/test_devices/test_specific_device.py
Enable admin to query device by name
At the moment, one can query a device by id, this PR makes it possible to query a device by name
- git pull and checkout to the branch ft-query-device-by-name-166285928
-  run application
```
query{
deviceByName(deviceName:"apple tablet"){
id
name
deviceType
room{
name
}
}
}
```
[166285928](https://www.pivotaltracker.com/story/show/166285928)
None
=> #166285928 Enable admin to query device by name

api/devices/schema.py, fixtures/devices/devices_fixtures.py, tests/test_devices/test_create_device.py
- Sets device location to location from admin's token
- Removes location field from createDevice mutation
When an admin is adding a new device, the device location field should be set to the location that is in the admin's token.
3. checkout to branch `ch-refactor-create-device-165907624`
3. run the following query:
```
mutation {
createDevice (
name: "samsung s3rt7",
roomId: 1,
deviceType: "tablet"
) {
device {
name
location
}
}
}
```
[#165907624](https://www.pivotaltracker.com/story/show/165907624)
The `location` field would be the location in your token.
=> #165907624 Refactor create device mutation

api/room_resource/schema.py, fixtures/room_resource/resource_fixture.py, tests/test_room_resource/test_resource_by_name.py
Enables an admin to search for a resource using resource name
- query for a resource using resource name
- test query to fetch resource by name
2. Setup project according to `Readme.md`
3. checkout to branch `ft-search-resource-by-name-166285961`
3. on insomnia send query
```
{
resourceByName(name: "table") {
name
room {
room {
name
}
quantity
}
}
}
```
[#166285961](https://www.pivotaltracker.com/story/show/166285961)
=> #166285961 search resource by name

api/events/schema.py, fixtures/analytics/query_all_analytics_fixtures.py, fixtures/events/event_checkin_fixtures.py, fixtures/location/all_locations_fixtures.py, fixtures/location/rooms_in_location_fixtures.py, fixtures/room/create_room_fixtures.py, fixtures/room/filter_room_fixtures.py, fixtures/room/query_room_fixtures.py, helpers/devices/devices.py, tests/base.py, tests/test_events/test_event_checkin.py
updates device last seen when checking in to an event or when canceling an event
- modify event check-in mutation
- modify cancel event mutation
- fix tests
2. Setup project according to `Readme.md`
3. checkout to branch `ft-device-last-seen-to-equal-checkin-time-166539920`
4. on insomnia to check-in to an event send the mutation
```
mutation {
eventCheckin(calendarId: "andela.com_38393338303730373538@resource.calendar.google.com", eventId: "041t6mhogr8cq7i8vvr2h36d9p", eventTitle: "First LFA On-Boarding", startTime: "2019-04-25T05:00:00-07:00", endTime: "2019-04-25T06:00:00-07:00", numberOfParticipants: 13, checkInTime: "2019-04-25T05:02:00-07:00") {
event {
eventTitle
room{
name
devices{
name
lastSeen
}
}
}
}
}
```
5. …
=> #166539920 update device last seen to equal checkin time value

api/devices/schema.py, fixtures/devices/devices_fixtures.py, tests/test_devices/test_all_devices.py
Enable Admins filter devices by labels
When an admin passes the `device_labels` field in the `allDevices` query, it filters the devices based on that label or labels (separated in commas).
3. checkout to branch `ft-enable-admin-filter-devices-166409230`
3. run the following query:
```
query {
allDevices(
deviceLabels: "1st Floor"
){
name
}
}
```
[#165907624](https://www.pivotaltracker.com/story/show/166409230)
The `location` field would be the location in your token.
=> #166409230 Enable Admins filter devices by labels

api/user/schema.py, fixtures/user/user_fixture.py, tests/test_user/test_query_user.py
Allow admin to search users by name
In order to ease navigating to a specific user, this PR makes it possible to search for a specific user by name
- git pull and checkout to the branch ft-query-user-by-name-166285991
-  run application
```
query{
userByName(userName:"onyeka mmakwe"){
email
name
location
}
}
```
[166285991](https://www.pivotaltracker.com/story/show/166285991)
None
=> #166285991 Allow admin to search users by name

api/room_resource/schema.py, fixtures/room_resource/get_room_resource_fixtures.py, helpers/room_filter/room_filter.py, tests/test_room_resource/test_get_resource_list.py
Enables an admin to filter resources by labels like buildings, floors, wings.
- Add tests
- Add `resourceLabels` to query to enable filtering by building, floors or wings.
2. Cd into the cloned repo and checkout to `ft-filter-assigned-resources-by-wings-floors-building-166409352` branch
3. Run the migration to setup the database (if you haven’t)  
5. Run the query below to filter resource by labels
```
{
allResources(resourceLabels:"Office 1"){
resources{
name
}
}
}
```
Currently, the `allResources` query returns a list of all resources in the platform. This PR introduces a filter mechanism using the labels like building, floors or wings to filter resources (usually assigned to a room) that match the filter criteria. The …
=> #166409352 Implement resource filtering by labels

api/room/schema_query.py
Fix bug on querying rooms
Currently, when we try to return a room by running its query we are able to return rooms that have been archived. This PR updates the query to only return rooms with an active state.
3. checkout to branch `bg-get-room-by-name-166438308`
4. When using Docker `make build`
5. run queries
` {
getRoomByName(name:"Kampala"){
name
}
}`  Room with active state
`
{
getRoomByName(name:"New York"){
name
}
}` Room with Archived state
[#166438308](https://www.pivotaltracker.com/story/show/166438308)
N/A
Screenshots
=> #166438308  fix get_room_by_name query to filter out archived rooms

api/response/schema.py, api/response/schema_query.py, fixtures/response/room_response_fixture.py, helpers/response/create_response.py, tests/test_response/test_resolved_responses.py
This pull request:
- Enables admin to query only resolved responses
- Enables admin to mark multiple responses as resolved/unresolved at once
- checkout to branch `story/CON-86-enable-admin-resolve-multiple-responses`
- on insomnia
to fetch all resolved responses send the query:
```
{
allRoomResponses(resolved: true) {
responses {
roomName
response {
responseId
response {
__typename
... on Rate {
rate
}
... on SelectedOptions {
options
}
... on TextArea {
suggestion
}
... on MissingItems {
missingItems {
name
id
}
}
}
resolved
}
totalResponses
}
}
}
```
to fetch resolved room responses send the query:
```
{
roomResponse(roomId: 18, resolved: true) {
roomName
response {
responseId …
```
=> CON-86-story Enable admin resolve/unresolve multiple responses at once

api/user/schema.py, fixtures/user/user_fixture.py, helpers/auth/authentication.py, tests/test_user/test_change_user_location.py
This pull request ensures an admin can change the location of a user.
Use the mutation below to change a user's location
```
mutation {
changeUserLocation(email: "david.njoki@andela.com", locationId: 3) {
user {
name
location
}
}
}
```
[CON-170](https://andela-apprenticeship.atlassian.net/browse/CON-170)
=> CON-170-story(user-location): enable admin change user location

api/location/models.py
This pull request fixes the `allLocations` query to return only rooms that are active
- checkout to branch `story/CON-119-enable-admin-to-invite-users-as-admins`
- on insomnia
to fetch all locations use the query:
```
{
allLocations{
name
rooms{
name
state
}
}
}
```
[CON-182](https://andela-apprenticeship.atlassian.net/browse/CON-182)
=> CON-182 Fix deleted rooms showing on locations

api/question/schema.py, fixtures/questions/get_question_fixtures.py
When a question is created, the is_active field is FALSE by default. The admin needs to view all questions in order to activate a question.  Currently, the all questions query returns only active questions. The query needs to fetch all active an inactive questions to enable the admin to activate the questions from the front end. This PR fixes this issue.
Checkout to branch bug/CON-139-fix-questions-query.
Run the following query:
```
{
allQuestions{
id
questionType
questionTitle
questionResponseCount
checkOptions
isActive
state
}
}
```
**Fetch all questions**
[CON-139](https://andela-apprenticeship.atlassian.net/jira/software …
=> CON-139 Fix questions query

api/user/schema.py, fixtures/user/user_fixture.py, helpers/email/email.py, helpers/email/email_setup.py, templates/change_role.html, templates/invite.html, tests/test_user/test_change_user_role.py, tests/test_user/test_invite_email.py
This pull request sends email notifications to users:
- When they are being invited to join Converge
- When their role is changed
- checkout to branch `story/CON-119-enable-admin-to-invite-users-as-admins`
- on insomnia
to invite a user to Converge, use their valid Andela email to send the mutation:
```
mutation {
inviteToConverge(email: "user.email@andela.com") {
email
}
}
```
to change a user role, use their valid Andela email to send the mutation:
```
mutation {
changeUserRole(email: "user.email@andela.com", roleId: 1) {
user {
name
email
location
roles {
role
}
}
}
}
```
[CON-119](https://andela-apprenticeship.atlassian.net/browse/CON-119)
=> CON-119 Enable admin to invite users as admins

api/user/schema.py, fixtures/room/create_room_fixtures.py, fixtures/user/user_fixture.py, fixtures/user_role/user_role_fixtures.py, helpers/auth/authentication.py, tests/test_rooms/test_create_room.py, tests/test_user/test_query_user.py, tests/test_user_roles/test_query_user_role.py
This pull request adds authentication decorator to the `resolve_user` method. Currently, this endpoint is not protected and this precludes any new user trying to access it from being saved to the database as in the case of protected endpoints. 
Also, the details of some users are not returned from the Andela API. This means such users are saved into our DB without location details. This PR ensures the location of such users defaults to `Nairobi`. 
- checkout to branch `bug/secure-get-user-endpoint`
- delete your user details on the local database
- on insomnia send a request to the endpoint below
```
query {
user(email: "validandelaemail@andela.com") {
email
name
}
}
```
Please …
=> CON-205 Fix new user account creation error

helpers/auth/authentication.py
The issue of `null` user location in the DB is not yet fully fixed. Users with `null` location value on the Andela API still have their location set to `null` in our DB. This PR ensures the location field is default to Nairobi whenever there is no valid location detail from the Andela API.
[CON-210](https://andela-apprenticeship.atlassian.net/browse/CON-210)
=> CON-210 Fix null user location

api/structure/schema.py
This Pull request enables a non-admin user to fetch an office structure
On our application, only super admin user or admin user can query the office structure, this PR ensures that a regular user is authenticated to allow access to the office structure as well. 
3. checkout to branch `story/CON-208-enable-regular-user-to-query-office-structure`
4. For token authorization, make sure that the email used is valid and already exists in our database and it's of role_id =  1(default user)
- use the query below to get all office structures
```query {
allStructures {
name
tag
locationId
}
```
- use the query below to get a single office structure …
=> CON-208 Enable regular user to query office structure

tests/base.py, tests/test_rooms/test_create_room.py
Currently, API calls are made to google calendar during tests, as there is an event listener in the room model that validates `calendar_ids` whenever a new row is inserted. Since our test `setUp` method creates rooms, and since this method is called per test case, this slows down our tests.  This PR ensures the google calendar API call is mocked, thereby, significantly reducing test run time.
- Checkout this branch and run tests
- Checkout `develop` and run tests
- Compare the runtime
[CON-231](https://andela-apprenticeship.atlassian.net/browse/CON-231)
=> CON-231 Mock test calendar api calls

api/analytics/all_analytics_query.py, api/devices/schema.py, api/events/schema.py, api/location/schema.py, api/notification/schema.py, api/office/schema.py, api/question/schema.py, api/response/schema.py, api/response/schema_query.py, api/room/schema.py, api/room/schema_query.py, api/room_resource/schema.py, api/structure/schema.py, api/tag/schema.py, api/user/schema.py, tests/base.py, utilities/calendar_ids_cleanup.py
This pull request renames `Super_Admin` role to `Super Admin`
- checkout to branch `story/CON-119-enable-admin-to-invite-users-as-admins`
- ensure `Super_Admin` role on the database is changed to `Super Admin`
- if you do not have Super Admin role use the mutation below to create:
```
mutation {
createRole(role: "Super Admin") {
role {
id
role
}
}
}
```
- on insomnia run any super admin query or mutation eg:
```
{
allAnalytics(startDate: "apr 13 2019", endDate: "may 11 2019" locationId:1) {
autoCancellationsPercentage
bookings
analytics {
roomName
cancellations …
```
=> CON-218 Remove the underscore in the Super_Admin role name

helpers/email/email.py
This PR adds the capability to send both the organizer or host and invitees an email notification when the event is auto-canceled. The event is auto-canceled after 10 minutes of no check-in.
This is a new feature.
- Clone the repo: git clone https://github.com/andela/mrm_api.git.
- Setup the project as per the ` README.md `.
- Checkout to branch ` story/CON-171-send-invitees-email-when-event-is-autocancelled `.
- Create an event on your google calendar and invite a few people. While creating your event on google calendar, add the mrm-api ` converge dummy room` as your room.
- Run the following mutation to sync your new event with the database ` syncEventData `.
```
mutation {
syncEventData{
message
}
}
```
- Run the following mutation to trigger event cancellation.
```
mutation { …
```
=> CON-171 Send email to invitees when event is auto-canceled

app.py, tests/base.py, tests/test_logs/test_logs_endpoint.py, utilities/file_reader.py
This PR enables the  Super Admin to view backend logs through a HTTP get request. The most recent logs appear at the top. Currently, we have to wait for the dev ops team to provide us with the log file on the staging app whenever debugging is required. This features enables one to view the logs immediately thus reducing the debugging time.
Checkout to branch story/CON-207-display-backend-logs.
On your Insomnia, go to url `localhost:8000/logs` and send a `GET REQUEST` using a `Super Admin token`. 
[CON-207](https://andela-apprenticeship.atlassian.net/jira/software/projects/CON/boards/15/backlog?label=backend&selectedIssue=CON- …
=> CON-207 Display backend logs through http

app.py, docker/prod/mrm_api.conf, utilities/file_reader.py
Currently, the mrm.err.log file on staging and production isn't found as it is never created. We need to create this file on the two deployed environments so as to enable viewing of the logs. 
Checkout to branch bug/CON-243-fix-display-of-logs-feature.
On your Insomnia, go to url `localhost:8000/logs` and send a `GET REQUEST` using a `Super Admin token`. 
Feature should still display logs
[CON-243](https://andela-apprenticeship.atlassian.net/jira/software/projects/CON/boards/15/backlog?label=backend&selectedIssue=CON-243)
=> CON-243 Fix the display of logs

api/office_structure/schema.py, fixtures/office_structure/query_structure_fixture.py, schema.py, tests/test_office_structure/test_query_structure.py
We want to be able to get the full path of a node. i.e. the node, its parent, its grandparent, ....  root_node. The node could be a `room`, `floor` or `wing` in the structure.
If for example, you pass a `node` named `Mara`, it should return `Mara -> Right Wing -> 4th Floor -> ET`
- Make sure you have a valid structure in your db. You can refer to [480](https://github.com/andela/mrm_api/pull/480)
- Use the query below to get the full path of a `node/room` called `Mara`.
- The `order` field is optional and is `DESC` by default.
```
query {
nodePathByName(nodeName: "Mara", order: ASC) {
id
name
tag
parent {
name
}
}
}
```
[CON-249](https://andela-apprenticeship.atlassian.net/browse/CON-249)
=> CON-249 Get full path of node

fixtures/role/role_fixtures.py, fixtures/user/delete_user.py, helpers/auth/authentication.py, tests/base.py, tests/test_role/test_query_role.py
This PR stops some unnecessary api calls to Andela api anytime a user tries to use one of our mutations or queries. Currently when a user logs into converge and makes a request for a resource we make an api call to the Andela api each time, also the `user_roles` helper has been bloated to do much more that it should do. This aims to fix those issues and also break down the `user_roles` function into smaller functions.
Checkout to branch chore/CON-213-refactor-authentication-module.
On your Insomnia, try performing any activity that requires a token and everything should work as expected.`.  …
=> CON 213 Refactor user authentication module

api/user/schema.py, fixtures/user/user_fixture.py, helpers/auth/authentication.py, tests/test_user/test_set_user_location.py
This Pull request makes it possible for users to set a new location after sign up. Currently, when new users join the application they have a token set for the from the Andela API which is not always correct. we want to stop the autosave and enable users set for themselves
3. checkout to branch `story/CON-254-allow-users-set-location`
4. run the following query to set a new location for a user who doesn't have a location set. 
```
mutation {
setUserLocation(locationId: 2){
user{
email
}
}
}
```
[CON-254](https://andela-apprenticeship.atlassian.net/browse/CON-254)
=> CON 254 Implement functionality to enable users set their location

api/office_structure/schema.py, fixtures/office_structure/delete_office_structure_fixtures.py, tests/test_office_structure/test_delete_node.py
This feature enables the super admin or admin user to delete a node by use of its id. 
Checkout to branch story/CON-252-delete-node-by-id.
Make sure you have a valid structure in your db. You can refer to  [480](https://github.com/andela/mrm_api/pull/480)
Use the query below to delete an existing node:
```
mutation{
deleteNode(nodeId:"c56a4180-65aa-42ec-a945-5fd21dec0536"){
node{
id
name
}
}
}
``` 
[CON-252](https://andela-apprenticeship.atlassian.net/browse/CON-252)
=> CON-252 Delete node by its id

api/user/schema.py, fixtures/analytics/query_all_analytics_fixtures.py, fixtures/role/role_fixtures.py, fixtures/user/user_fixture.py, helpers/user_role/restrict_admin.py, tests/base.py, tests/test_analytics/test_all_analytics_query.py, tests/test_logs/test_logs_endpoint.py, tests/test_user/test_change_user_role.py
This Pull request restricts an admin from creating a super admin. 
On our application, a super admin can be created by an admin, this PR ensures that an admin is restricted from creating a super admin. 
3. checkout to branch `story/CON-168-stop-admin-to-create-super-admin`
4. run the following query to change the role of a user. Make sure the email is valid and already exists in our database and its role_id = 2 or 1
```
mutation{
changeUserRole(email:"email@andela.com", roleId: 3){
user{
id
roles{
id
}
}
}
}
```
[CON-168](https://andela-apprenticeship.atlassian.net/browse/CON-168)
=> CON-168 Restrict an admin from creating super admins.

api/user/schema.py, fixtures/user_role/user_role_fixtures.py, tests/test_user/test_create_user.py, tests/test_user_roles/test_create_user_role.py
This Pull request checks if a user was already assigned a role and doesn't allow for a duplicate in the role's table. 
The user was allowed to be assigned two roles, now a user should only have one role.  
3. checkout to branch `story/CON-200-validating-duplicates`
4. run the following query to create a user role. Make sure this user already exists and has at least one role assigned to him/her
```
mutation{
createUserRole(userId: (user-role), roleId: 2){
userRole{
id
roles{
id
}
}
}
}``
[CON-200](https://andela-apprenticeship.atlassian.net/browse/CON-200)
=> CON-200 Prevent users from having multiple roles

docker/prod/mrm_api.conf
Currently, the mrm.err.log file on staging and production is created. However, the logs file shows recurring errors that `the connection is in use`. This error is recurring due to trying to run the app again on the same port that is currently in use in the deployed environments. The removal of the command `command=/bin/bash -c '. /app/docker/prod/start_gunicorn.sh'` should ideally remove this recursion. 
Checkout to branch bug/CON-243-fix-display-of-logs-feature.
On your Insomnia, go to url `localhost:8000/logs` and send a `GET REQUEST` using a `Super Admin token`. 
Feature should still display logs …
=> CON-243 Fix log configuration error

api/user/schema.py, helpers/auth/authentication.py, tests/base.py, tests/test_analytics/test_all_analytics_query.py
Currently, when a deleted user tries to set their location using the `setLocation` mutation we get an error, this PR handles that error and returns a descriptive error message
- delete a user using the `deleteUser` mutation and the n try to set a location for the user.
[CON-285](https://andela-apprenticeship.atlassian.net/browse/CON-285)
=> CON-285 Fix error when deleted user tries to set their location

docker/prod/mrm_api.conf
Reverts andela/mrm_api#489
This PR causes instability on the staging api.
=> Revert "CON-243 Fix log configuration error"

api/user/schema.py, fixtures/user/delete_user.py, tests/test_user/test_delete_user.py
This PR extends the `DeleteUser Mutation` by providing an option for the total removal of a user from the DB. This task allows for smooth simulation of the new onboarding experience feature currently being implemented by the frontend team on the staging-api.
Use the below mutation while setting `remove` to `true`
```
mutation {
deleteUser(email: "andelauser@andela.com" remove: true) {
user{
id
email
location
roles {
id
role
}
}
}
}
```
[CON-292](https://andela-apprenticeship.atlassian.net/browse/CON-292)
=> CON-292 Allow hard delete of users

api/office_structure/schema.py, fixtures/office_structure/update_node_fixtures.py, tests/test_office_structure/test_update_node.py
This PR implements the update node for a structure, this allows us to update a single node of the structure from the backend instead of being implemented from the front end. 
- git pull and checkout to the branch story/CON-284-edit-office-structure
- ensure you have the latest migrations
- Use the below mutation to update a node in your development environment
```
mutation {
updateNode(nodeId: "C56A4180-65AA-42EC-A945-5FD21DEC0518",
name: "Epic Tower", tag: "Building Name") {
node {
name
tag
}
}
}
```
[CON-284](https://andela-apprenticeship.atlassian.net/browse/CON-284)
=> CON-284 Update a structure node

api/room/models.py
Currently, whenever we delete a device or archive it, we still get that device when we query the rooms. This Pr adds logic to filter the returned devices such that only devices with the active state is returned.
- git pull and checkout to the branch bug/CON-299-fix-deleted-room-device
- archive or delete a device attached to a room_id  
- Query the rooms, and it should not return the device.
Example query, to query all room names and devices
```
{
allRooms {
rooms {
name
devices {
name
}
}
}
}
```
[CON-299](https://andela-apprenticeship.atlassian.net/browse/CON-299)
=> CON-299 Fix deleted room device

helpers/auth/admin_roles.py, helpers/calendar/all_analytics_helper.py, helpers/calendar/analytics_helper.py, helpers/calendar/events_sql.py
Currently, analytics data does not consider the user's time zone and the time zone associated with the event. This PR ensures time zone is put into consideration before returning analytics data.
- You can book an event in any of the dummy/test rooms for any time.
- Sync your `DB` to retrieve the event. 
- Make the `all analytics query` and confirm your event is included.
```
query {
allAnalytics(startDate: "Aug 10 2019", endDate: "Aug 12 2019"){
bookings
analytics{
roomName
cancellations
checkins
appBookings
events{
durationInMinutes
}
}
bookingsCount {
period
totalBookings
}
}
}
```
[CON-273](https://andela-apprenticeship.atlassian.net/browse/CON-273)
=> CON-273 Fix analytics time zone issue 

api/events/schema.py, api/room/schema_query.py, fixtures/room/query_room_fixtures.py, tests/test_rooms/test_query_rooms.py
This PR adds the capability to query test remote-rooms on the staging environment and query actual remote-rooms on the production environment.
The staging environment is set to ` development ` while the production ` environment ` is set to production.
This is a Fix.
Follow these steps to test this out locally.
- Clone the repo: git clone https://github.com/andela/mrm_api.git.
- Setup the project as per the ` README.md `.
- Checkout to branch ` bug/CON-211-fix-meeting-room-issue-on-staging-environment`.
- Run ` make kill ` if necessary.
- Go to your ` .env ` file and switch your environment to ` production `.
- Set your environment to either ` production ` using this command ` export ` export APP_SETTINGS=production `.
- Restart your docker container.
- Run ` make build `.
- Run ` make …
=> CON-211 Fix meeting room issue on staging

helpers/remote_rooms/remote_rooms_location.py
Currently, it is impossible for an admin in Kigali to fetch calendar rooms in the location. This PR fixes this issue
- change your location to `Kigali` and use the below query
- before: you will receive an error
- now: you should be able to see remote rooms in `Kigali`
```
query {
allRemoteRooms  {
rooms {
name
calendarId
}
}
}
```
[CON-326](https://andela-apprenticeship.atlassian.net/browse/CON-326)
=> CON-326 Fix remote rooms for Kigali
