.gitignore
Readme.md

- This PR creates the initial product readme.md. Included are some details about the mrm-api. 
- The Readme is to be updated as the product is being built. New sections will be added when the need arises.
- The Readme can be viewed on at this branch `ch-initial-product-Readme.md-156461913`
- The key sections  requested were:
-  Product overview (what the product does)
-  development set up(how to set up locally)
-  built with ( tools used to build the product)
-  contribution guide
-  Running Migrations
- #156461913

#156461913 Initial product Readme.md 

---

.env.example
.gitignore
config.py

- add .gitignore file
- add .env.example file
- modify config.py
n/a
n/a
What are the relevant pivotal tracker stories?
[156461015](https://www.pivotaltracker.com/n/projects/2154921)

Set config options as env variables

---

.circleci/config.yml

- Enables Continuous Deployment from the Develop branch to GCP
- This happens when there is a new merge to the develop branch (or a new commit to it)
- When a new commit has been made to the develop branch
- Wait about 10 mins
- Explore your new changes at the URL: [Converge API URL](<https://converge-api.andela.com/>)
https://www.pivotaltracker.com/story/show/157627508

#157627508: CircleCI Continuous Deployment to GCP

---

.circleci/config.yml
Readme.md
requirements.txt

- Sends Coverage Reports to Coveralls
- Places Coveralls Scores on github Readme
[157895403](<https://www.pivotaltracker.com/story/show/157895403>)

#157895403 integrate Coveralls

---

api/room/schema.py
app.py
fixtures/room/room_fixtures.py
requirements.txt

- Allow Cross Origin Requests
- The back end currently does not allow requests from origins other than its own: This prevents the 
front end or android clients from interacting with the back end and thus cannot make use of the 
various queries/mutations currently present:
- N/A
- N/A
- #158212180
Screenshots (if appropriate)
- N/A

#158212180 Allow Cross Origin Requests

---

.circleci/config.yml

- Modifies CircleCI config to reenable Continuous Deployment to GCP
[158211220](<https://www.pivotaltracker.com/story/show/158211220>)
- PR is part of a series of PR updates made to the instances on GCP and backend 
>- [Infrastructure PR](https://github.com/andela/mrm-deployment-scripts/pull/9)
>- [Frontend PR](https://github.com/andela/mrm_front/pull/27)
- PR is necessary for Continuous Deployment
- Merging of this PR is urgent as subsequent merges to develop (before this PR is merged) would fail

#158211220: upgrade infrastructure from zonal to regional

---

.codeclimate.yml
api/room/schema.py
helpers/calendar/calendar.py

What does this PR do?
Fix codeclimate Issues on backend
What are the relevant Pivotal Tracker stories?
ID: #159357284
Story: Fix codeclimate Issues on backend

 #159357284 Fix codeclimate Issues on backend

---

app.py
manage.py

- This PR report errors from the API to `bugsnag` dashboard and also notify slack
- Import a module that doesn't exist
- #159326097
Notifitication on slack channel
Bugsnag Dashboard

chore(monitoring): Set up monitoring for application

---

requirements.txt

include bugsnag dependency in requirements
[159620974](<https://www.pivotaltracker.com/story/show/159620974>)

#159620974 modify requirements

---

api/room/schema.py
api/room_resource/schema.py
helpers/pagination/paginate.py

- This PR refactors pagination code to prevent code duplication.
- Run `allRooms` or `allResources` queries with specified pagination's page and perPage
#159654368

#159654368 Refactor pagination code

---

api/floor/schema.py
fixtures/floor/get_rooms_in_floor_fixtures.py

- This PR  ensures that when the `getRoomsInAFloor` is run, it returns the list of all rooms in the floor 
- Run `getRoomsInAFloor` query 
- #159652420

#159652420 Fix get rooms in a floor query

---

api/location/schema.py
fixtures/location/nonexistant_location_id_fixtures.py
fixtures/location/rooms_in_location_fixtures.py

The PR ensures when a query for rooms in a location is run, a list of rooms in that location is returned.
- Run getRoomsInALocation query
#159652372

#159652372 Fix get rooms in a location query

---

.circleci/config.yml

[159794383](https://www.pivotaltracker.com/story/show/159794383)

#159794383 fix backend instance group name

---

api/user/schema.py

- This PR refactors user pagination code to prevent code duplication.
- Run `users` query with specified pagination's page and perPage
#159654368

#159654368 Refactor user pagination code

---

api/room/schema.py
api/room_resource/schema.py
api/user/schema.py
helpers/pagination/paginate.py
tests/base.py
tests/test_user_roles/test_query_user_role.py

- Test the affected queries at localhost:5000/mrm
- An improvement score should be noted on the code climate maintainability badge. 
#159882291

#159882291 fix duplication issues on back end.

---

api/office/schema.py
api/room/schema.py
helpers/auth/admin_roles.py
tests/test_office/test_delete_office.py

- Test the affected mutation (`deleteOffice`) at localhost:5000/mrm
- An improvement score should also be noted on the code climate maintainability badge. 
#160451269

#160451269 fix duplication issues on the back end.

---

.circleci/config.yml

This PR corrects the instance group for the application deployment
- Replace instance group
- Run build on staging
N/A
#160614564

#160614564 Change instance group in deploy-job

---

.circleci/config.yml

[161078715](https://www.pivotaltracker.com/story/show/161078715)

#161078715 Deploy to infrastructure

---

.circleci/config.yml
.circleci/csv_parser.py
.circleci/deployment_report.sh
.circleci/gcloud_bucket.sh
.circleci/update_csv.py
tox.ini

This PR auto generates weekly deployment reports
- add cron job to circleci
- update gcloud bucket on every deployment
- integrate slack for notification
A deployment-report job will be run every Friday by 15:00 and notify slack after it's completion
N/A
#159428046

#159428046 Create auto generated devops report

---

fixtures/room/room_calendar_ids_cleanup.py
helpers/auth/authentication.py
helpers/auth/validator.py
schema.py
tests/test_rooms/test_room_calendar_ids_cleanup.py
utilities/calendar_ids_cleanup.py

- Fixes analytics errors by adding a cleanup file which allows admin to clean up the db of invalid ids
- Test the mutation at `localhost:5000/mrm`
- Run `validateRoomsCalendarIds` query to remove all rooms with invalid ids from the database
[#161409776](https://www.pivotaltracker.com/story/show/161409776)
1. Response when all rooms have valid Calendar IDs
2.Database with invalid keys
3. Query to clean db of rooms with invalid calendar IDs
4. Database after cleanup

#161409776 Delete rooms with invalid calendar ids

---

.circleci/config.yml
.circleci/notify_slack.sh

This PR ensures that the pipeline workflow notification are job specific to give clarity on results
- create notification script
- make notification script run on conditions
A slack notification is sent after every job 
N/A
[#161428547](https://www.pivotaltracker.com/story/show/161428547) - Converge PT Board
[#161443974](https://www.pivotaltracker.com/story/show/161443974) - DevOps PT Board

#161428547 make build notification branch specific backend 

---

helpers/calendar/analytics.py
helpers/calendar/analytics_helper.py
utilities/calendar_ids_cleanup.py

Code climate currently highlights 18 code smell issues among them long modules. This PR fixes these issues and reduces the code smells 
- Navigate to code climate website https://codeclimate.com/repos/5b0c1a7f82b58e02d000118e and click on the overview tab.
[#161296049](https://www.pivotaltracker.com/story/show/161296049)

#161296049 Fix Code Climate Issues

---

api/analytics/analytic_report.py
api/analytics/analytics_request.py
api/analytics/write_files.py
app.py
helpers/auth/authentication.py
requirements.txt

This PR enable export of analytics report into a CSV file format and JSON format when the file format is not specified
- Test the queries at `localhost:5000/analytics`
- Run a POST request with the following params.  
- `timeMin`
- `timeMax`
- `fileType`
[Admin can export the analytics report as CSV file](https://www.pivotaltracker.com/n/projects/2154921/stories/161054950)

#161054950 Export analytics report as CSV file

---

api/analytics/analytic_report.py
api/analytics/analytics_request.py
api/analytics/write_files.py
app.py
helpers/auth/authentication.py
requirements.txt

Export  room analytics report as PDF file.
- Ensure that `wkhtmltopdf` is installed in your machine by running the command `brew install Caskroom/cask/wkhtmltopdf`   in your terminal.
- Run the server. 
- Test the queries at `localhost:5000/analytics`
- Run a POST request with the following params( `start_date`,`end_date` and `file_type` )  the file is downloaded and displayed as shown below
[#161054920](https://www.pivotaltracker.com/story/show/161054920)

#161054920 Export room analytics report as PDF file 

---

app.py
templates/index.html

Adds a index file to enable verification of domain
#161838908

#161838908 add index html file to verify domain

---

templates/index.html

Confirms owneship of the staging domain by converge.notifications @andela.com user
Add meta tag to the index.html to show ownership
N/A
N/A
https://www.pivotaltracker.com/story/show/161838908
N/A

161838908: confirm domain for calendar notifications

---

app.py
config.py
helpers/socket/socketio.py
manage.py
requirements.txt
templates/index.html

Implementation of a real-time progress bar using `flask-socketio`and `flask-executor`
- install the dependencies from _requirements.txt_ `pip install -r requirements.txt`
- Run the server `http://127.0.0.1:5000/analytics` & the client ``http://127.0.0.1:5000/``
relevant pivotal tracker stories?
[#162376808](https://www.pivotaltracker.com/story/show/162376808)
Gif

#162376808 Realtime progress bar 

---

api/block/schema.py
api/floor/schema.py
api/response/schema.py
api/room/schema_query.py
helpers/auth/admin_roles.py

Fix code maintainability issues raised by code climate. Improves the score of the report.
Refactor sections of code that has similar blocks of code and cognitive complexity
Check the code maintainability report on code climate
Not applicable
[#162788994](https://www.pivotaltracker.com/story/show/162788994)

#162788994 improve code maintainability

---

alembic/versions/1486dc6d0b6b_add_activation_field_to_questions_.py

Fix alembic errors.
To fix it you just have to adjust the `down_revision` of your migration to be that of the latest one. 
Clone the branch and run `alembic stamp head` followed with `alembic upgrade head` in the terminal.
Not applicable
#163110997

#163110997 Fix alembic errors

---

api/question/schema_query.py
fixtures/questions/create_questions_fixtures.py
tests/test_questions/test_view_question.py

- Adds a query to retrieve all feedback questions
```query {
allQuestions{
question
questionType
id
isActive
}
}
```
[#163141999](https://www.pivotaltracker.com/story/show/163141999)
N/A

#163141999 Query all questions

---

api/floor/schema.py
fixtures/floor/get_floors_fixures.py
tests/test_floors/test_query_floors.py

- Paginate the response coming from the floors
The task is to allow the admin to be able to scroll through all the available floors .
```
query {
allFloors(page: 1, perPage: 4) {
floors {
name
rooms {
name
}
}
queryTotal
hasNext
hasPrevious
}
}
```
None
[#162701212](https://www.pivotaltracker.com/story/show/162701212)
**Questions:**
None

#162701212 Paginate the floors response

---

.gitignore
Makefile
Readme.md
__init__.py
docker/dev/Dockerfile
docker/dev/create_test_db.sh
docker/dev/docker-compose.yml
docker/dev/start_app.sh
docker/dev/start_db_import.sh
docker/dev/start_gunicorn.sh
docker/dev/start_initial_migrations.sh
docker/dev/start_migrations.sh
docker/dev/start_redis.sh
docker/dev/start_tests.sh
fixtures/office/office_fixtures.py
mrm_api.conf
tests/test_office/test_create_office.py

- Build the application with `make build`
- Run the application with `make run-app`
- Running application can be visited on `http://localhost:8000`
- Run tests with `make test test=tox`
- Stop all services with `make down`
[#162516989](https://www.pivotaltracker.com/story/show/162516989)

#162516989 Containerize converge backend with docker

---

docker/dev/start_db_import.sh

- After building the application with `make build`
- Run `make import dump="<path to dump>"`
[#163324347](https://www.pivotaltracker.com/story/show/163324347)

#163324347 fix database imports

---

helpers/auth/authentication.py
helpers/connection/connection_error_handler.py

Handle exception raised when internet fails. `ConnectionError`
- turn off your wifi and make any request whether  graphql or rest.
[#163009012](https://www.pivotaltracker.com/story/show/163009012)
_Rest_request
_Graphql_ request

#163009012: Handle exception raised when internet fails

---

alembic/versions/c53edf85cda4_create_room_tags_model.py
alembic/versions/d2a4ba0089fa_add_missing_responses_table.py
api/tag/models.py

Fix import errors and multiple heads on develop
- Develop is currently failing due to an import error in api/tags/models.py. 
- There are also multiple heads. This PR fixes this issue.
-N/A
N/A
[#163449366](https://www.pivotaltracker.com/story/show/163449366)

#163449366: Fix import error and multiple heads

---

tests/test_response/test_user_response.py

Fixes an over-indentation bug 
**Description of Task to be completed?**
Removes extra indentation in the test file `test_user_response.py`. This was exposed by flake8
Run flake8 on the tests folder, it should not return any errors now
None
#163582215

#163582215 Remove extra indentation in test_user_response.py file

---

templates/index.html

- Updates the metadata for google-site-verification in templates/index
This change will enable the application domains(https://converge-api.andela.com) to be verified on the Google console API and Google search console using.
[#163590344](https://www.pivotaltracker.com/story/show/163590344)

#163590344 update google site verification

---

tests/test_devices/test_create_device.py

Change the names of the class and test in test-devices
Currently, the name of the class is `TestCreateRoom` and the test is `test-room-creation`. This though is a test for creating devices.
In case of bugs, it would be a bit difficult to know which test is failing exactly since two tests have the same name hence changing the name of the test create device
[#163587718](https://www.pivotaltracker.com/story/show/163587718)
- Not Applicable

#163587718 Change the names of the class and test in test-devices

---

api/user/schema.py

The changes in the PR enables tests to pass by changing the import of update_entity_fields from the validations file to the utility file
Currently, tests on develop are failing because of an import error.
The import is corrected in this PR.
N/A

#163356514 Fix import error in the users/schema.py file 

---

docker/prod/Dockerfile

[#163589178](https://www.pivotaltracker.com/story/show/163589178)

#163589178 Create backend container for production

---

api/response/schema_query.py

- Removes unnecessary room name returned when getting all rooms responses
Remove unnecessary room name
Rename some variables to be more descriptive
```
query {
allRoomResponses(filterBy: "name", upperLimit: 10, lowerLimit: 1) {
roomName
responses {
totalResponses
roomName
response {
responseId
suggestion
}
}
}
}
```
```
query {
allRoomResponses(filterBy: "name", upperLimit: 10, lowerLimit: 1) {
responses {
totalResponses
roomName
response {
responseId
suggestion
}
}
}
}
```
- Room name is no longer returned
None
[#163653304](https://www.pivotaltracker.com/story/show/163653304)
Before bug fix
After bug fix
**Questions:**
None

#163653304 Fix the all room responses query

---

api/response/schema_query.py
fixtures/response/room_response_fixture.py
fixtures/room/room_fixtures.py
tests/test_response/test_room_response.py

Revert "#163725518:Allow admin to search feedback response by room name"

---

api/room/schema.py
config.py
fixtures/room/update_firebase_token_fixtures.py
tests/test_rooms/test_update_firebase_token.py

* Create an endpoint for updating firebase token. 
*  Added a mutation to `api/rooms/schema.py` to take care of updating the token.
* Added tests for the same.
* git checkout to `ft-update-firebase-token-endpoint-163849509` and run the following query:
```
mutation{
updateFirebaseToken(firebaseToken:"hakjacjihihaehcfkuqehihjfieq-nanana",roomId:1){
room{
firebaseToken
}
}
}
```
```
{
"data": {
"updateFirebaseToken": {
"room": {
"firebaseToken": "hakjacjihihaehcfkuqehihjfieq-nanana"
}
}
}
}
```
* Not applicable
* Most booked rooms
[#163849509](https://www.pivotaltracker.com/n/projects/2154921/stories/163849509)

#163849509 Update Firebase Token

---

api/location/schema.py
api/office/schema.py
api/user/models.py
helpers/auth/admin_roles.py

The PR ensures that the admins should not be able to edit or delete locations that are not their own.
Currently, an admin can edit or delete a location where they do no reside. For example, an Admin in `Kampala` can update the location of `Nairobi`. This PR ensures that admins can only make changes to the location that they belong to.
- Pull the branch `bg-fix-edit-delete-location-163741006`
- run the command `make run-app`
- Run the `createLocation` query with Nairobi as the new location.
``` 
mutation{
deleteLocation(locationId:1){
location{
id
}
}
}
```
**OR**
```
mutation{
updateLocation(locationId: 1, name: "Nairobi", country: "Kenya", abbreviation: "KE"){ # noqa: E501
location{
name
abbreviation
country
}
}
}
```
The response should be similar to that shown …

#163741006 Fix edit and delete location

---

.circleci/config.yml
.circleci/notify_slack.sh

[#163981710](https://www.pivotaltracker.com/story/show/163981710)

#163981710 run tox tests in parallel

---

alembic/versions/ab83c84a325b_include_cascading_deletion.py

- fixes down revision version to fix multiple heads error
- Fix the multiple heads error in develop
- Run alembic stamp head and ensure you do not get multiple heads error.
N/A
[#164074898](https://www.pivotaltracker.com/story/show/164074898)
N/A

#164074898 Fix alembic down revision

---

.circleci/config.yml

[#164102299](https://www.pivotaltracker.com/story/show/164102299)

#164102299 add test credentials

---

api/events/schema.py
api/room/schema_query.py
fixtures/events/event_checkin_fixtures.py
helpers/calendar/events.py

- Refactor cancel event
- Make the cancel feature more robust by:
- Only updating canceled field to True if the event exists in the DB
- Add the event to the DB if it does not exist with the canceled set to True
- git pull branch `ch-refactor-cancel-event-163849430` and check it out
- use this query to retrieve all events and get you event_id
```
query{
analyticsForDailyRoomEvents(startDate:"Feb 14 2019", endDate:"Feb 15 2019"){
day
events{
eventId
eventSummary
eventSummary
startTime
endTime
roomName
noOfParticipants
}
}
}
```
- run this mutation below to cancel the event
- remember to update the mutation below with your event details
```
mutation {
cancelledEvent(
calendarId:"andela.com_3131313630383336383038@resource.calendar.google.com",
eventId:"22hojo3qqqr5jdaacr7610qjrg", …
```

#163849430 Refactor Cancel Event

---

docker/prod/Dockerfile
docker/prod/mrm_api.conf
docker/prod/start_app.sh
docker/prod/start_gunicorn.sh
docker/prod/start_redis.sh

[#164146422](https://www.pivotaltracker.com/story/show/164146422)

#164146422 update production image

---

.circleci/config.yml

[#164290405](https://www.pivotaltracker.com/story/show/164290405)

#164290405 Add backend testing credentials to circleci

---

.circleci/config.yml

[#164396343](https://www.pivotaltracker.com/story/show/164396343)

#164396343 reduce number of circleci tests

---

.circleci/config.yml

[#164428491](https://www.pivotaltracker.com/story/show/164428491)

#164428491 update circleci configuration

---

api/analytics/analytics_request.py
api/room/schema_query.py
fixtures/helpers/decorators_fixtures.py
fixtures/room/create_room_fixtures.py
fixtures/room/create_room_in_block_fixtures.py
fixtures/room/most_booked_room_least_booked_rooms_fixtures.py
helpers/auth/admin_roles.py
helpers/calendar/analytics_helper.py

Fixes the get most-booked and least-booked rooms GraphQL endpoints
GraphQL endpoints for most-booked and least-booked rooms return data different from same RESTful endpoints. This PR Modifies the GraphQL endpoints to return data similar to the RESTful endpoints.
Also enables a user to set a limit of the number of results they would like to see. 
Creates a single GraphQL endpoint that can be used to return both the most booked and least booked rooms analytics by specifying the `limit` and `criteria` or not to return analytics for all.
Pull the branch and run the following query.
analyticsForMostBookedRooms
````
{
analyticsForBookedRooms(startDate: "Feb 14 2019", endDate: "Feb 14 2019"){
analytics{
roomName
count
meetings
percentage
}
}
}
````
analytics for MostBookedRooms with a limit …

#164049106 Fix booked rooms GraphQL endpoints

---

api/location/schema.py
api/user/schema.py
fixtures/location/create_location_fixtures.py
helpers/auth/authentication.py
helpers/auth/error_handler.py
helpers/email/email.py
templates/location_success.html
tests/test_location/test_create_location.py

Display user-friendly messages such as "The database cannot be reached" when the app crashes due to a database error. 
- Pull this branch
- make the migrations as explained in the [README](https://github.com/andela/mrm_api/blob/develop/Readme.md)
- stop the server and try to run any mutation/query(to test for InternalError)
- delete a relation from the database and run a mutation that depends on that relation( to test for ProgrammingError)
* initial error message for InternalErrors
* new message for InternalErrors
* initial message for programmingErrors
* new error message for programmingErrors in production/staging environment
* new error message for programmingErrors in testing/development environment
`InternalError` is sometimes raised by drivers in the context of the database …

 #163754403 (V2) Display friendly message when app crashes due to database errors

---

.circleci/deploy_backend_to_kubernetes.sh

[#164574044](https://www.pivotaltracker.com/story/show/164574044)

#164574044 fix deployments to sandbox v2

---

.circleci/config.yml

[#164593766](https://www.pivotaltracker.com/story/show/164593766)

#164593766 fix deployment to sandbox

---

docker/prod/Dockerfile
docker/prod/mrm_api.conf
docker/prod/start_gunicorn.sh

[#164626619](https://www.pivotaltracker.com/story/show/164626619)

#164626619 Modify production image

---

.circleci/config.yml

[#164658741](https://www.pivotaltracker.com/story/show/164658741)

#164658741 Add push url environment variable

---

.circleci/config.yml

[#164659056](https://www.pivotaltracker.com/story/show/164659056)

#164659056 Add push url environment variable for sandbox

---

api/question/schema.py
fixtures/questions/create_questions_fixtures.py
tests/test_questions/test_create_question.py
tests/test_questions/test_update_question.py
utilities/validations.py

To validate the question types when creating and updating a question. The allowed question types are check, input and rate.
Chore (Validate question types)
- git pull and checkout branch `ch-validate-question-type-in-question-mutation-164462447`
````
mutation {
createQuestion(questionType: "Checks", question: "What is the third purpose?", questionTitle:"Nice1" startDate: "2019-04-21T13:32:15.753", endDate: "2019-05-22T13:32:15.753") {
question {
question
}
}
}
````
You will get an error message showing _Not a valid question type_
[#164462447](https://www.pivotaltracker.com/story/show/164462447)

#164462447 Validate question types on creating/updating a question

---

api/question/schema.py
fixtures/questions/create_questions_fixtures.py
tests/test_questions/test_create_question.py
tests/test_questions/test_update_question.py
utilities/validations.py

To validate the question types when creating and updating a question. The allowed question types are check, input and rate.
Chore (Validate question types)
- git pull and checkout branch `ch-validate-question-type-in-question-mutation-164462447`
````
mutation {
createQuestion(questionType: "Checks", question: "What is the purpose?", questionTitle:"Purpose" startDate: "2019-04-21T13:32:15.753", endDate: "2019-05-22T13:32:15.753") {
question {
question
}
}
}
````
You will get an error message showing _Not a valid question type_
[#164462447](https://www.pivotaltracker.com/story/show/164462447)

#164462447 Validate question types on creating/updating a question-v2

---

api/question/schema.py
fixtures/questions/get_question_fixtures.py
helpers/questions_filter/questions_filter.py
tests/base.py
tests/test_questions/test_view_question.py

Refactor get all questions endpoint to only return valid/active questions.
Chore (Refactor get all questions)
- git pull and checkout branch `ch-refactor-get-questions-164657362`
````
query {
allQuestions(startDate: "2018 Nov 20", endDate: "2018 Nov 28") {
id
questionType
questionTitle
question
startDate
endDate
questionResponseCount
response {
id
questionId
roomId
}
}
}
````
[#164657362](https://www.pivotaltracker.com/story/show/164657362)

#164657362 Refactor get questions endpoint

---

api/analytics/analytics_request.py
api/room/schema_query.py
fixtures/room/most_booked_room_least_booked_rooms_fixtures.py
helpers/auth/admin_roles.py
helpers/calendar/analytics_helper.py

Fixes the get most-booked and least-booked rooms GraphQL endpoints
GraphQL endpoints for most-booked and least-booked rooms return data different from same RESTful endpoints. This PR Modifies the GraphQL endpoints to return data similar to the RESTful endpoints.
Also enables a user to set a limit of the number of results they would like to see. 
Creates a single GraphQL endpoint that can be used to return both the most booked and least booked rooms analytics by specifying the `limit` and `criteria` or not to return analytics for all.
chore (Fix get most-booked and least-booked rooms GraphQL endpoints)
- git pull the branch `ch-most-and-least-booked-rooms-endpoints-v2-164049106`
- run the queries below.
`analytics for most booked rooms`
````
{
analyticsForBookedRooms(startDate: "Feb 14 …
```

#164049106(v2) Fix booked rooms GraphQL endpoints

---

api/question/schema.py
fixtures/questions/get_question_fixtures.py
helpers/questions_filter/questions_filter.py
tests/base.py
tests/test_questions/test_view_question.py

Refactor get all questions endpoint to only return valid/active questions.
Chore (Refactor get all questions)
- git pull and checkout branch `ch-refactor-get-questions-164657362`
````
query {
allQuestions(startDate: "2018 Nov 20", endDate: "2018 Nov 28") {
id
questionType
questionTitle
question
startDate
endDate
questionResponseCount
response {
id
questionId
roomId
}
}
}
````
[#164657362](https://www.pivotaltracker.com/story/show/164657362)

#164657362 Refactor get questions endpoint v2

---

.circleci/deploy_backend_to_kubernetes.sh

[#164987097](https://www.pivotaltracker.com/story/show/164987097)

#164987097 remove print statements

---

.circleci/deploy_backend_to_kubernetes.sh

[#164987121](https://www.pivotaltracker.com/story/show/164987121)

#164987097 remove print statements v2

---

api/room/schema_query.py

Fix a bug that returns the most booked rooms when querying for the least booked rooms
- A user should be able to query for the least booked rooms and in return get them from the least booked to the most booked.
- Clone the branch and follow the setup steps in the README.
- Checkout to the branch by using the command `git checkout bg-fix-least-booked-rooms-v2-164824376`
- Start the server and navigate to the right url.
- Make a query to get analytics for most booked rooms using the query below
- You can set a `limit` on the number of rooms you would like displayed. This should be an `int`
- You can also set a `criteria` on what you want to query. Use `most_booked` or `least_booked` as an argument. Omiting this argument will display `most_booked` by default.
```
{ …
```

#164824376 Fix least booked rooms bug (v2)

---

app.py

- Fix issues relating to sending POST request when accessing specified URL
- Refactor the previous implementation of the analytics endpoint
- Checkout by running `gco bg-modify-analytics-redirect-165440053`
- Start the server and navigate to `/notifications`
[#165440053](https://www.pivotaltracker.com/story/show/165440053)

#165440053 Analytics redirect fix chore(analytics redirect fix)

---

docker/prod/mrm_api.conf
docker/prod/start_app.sh

[#165116135](https://www.pivotaltracker.com/story/show/165116135)

#165116135 run gunicorn with bash

---

docker/prod/mrm_api.conf
docker/prod/start_app.sh

[#165329775](https://www.pivotaltracker.com/story/show/165329775)

#165329775 Run gunicorn with bash

---

api/room/schema_query.py
helpers/calendar/events.py

- Currently, there is an existing query that fetches daily events for version 1. The aim of this PR is to refactor the query to get the daily events based on the location of the user making the request.
- Refactor the query to return data based on user location
- Ensure existing tests passes
- Pull this branch `ch-query-daily-events-user-location-v1-165307595`
- Run a new migration to migrate to the v1 database
- Run mutations for `floors`, `location`, `offices` and `rooms`. If you need help running these mutations, check out the documentation for the [mrm endpoints](http://localhost:8000/mrm)
- Make sure to have different rooms already existing in the room model. You can make use of `push test room 1` and `push test room 2` as room names when creating these rooms.
- Run the following …

#165307595 Query daily events by user location

---

api/room/schema.py

Update firebase token mutation.
Modify the Update firebase token mutation to take params of calendar id and firebase token
- Checkout by running `gco bg-update-firebase-token-165530619`
- Make sure to have different rooms already existing in the room model
- Run the following query 
```
mutation{
updateFirebaseToken(firebaseToken:"hakjacjihihaehcfkuqehihjfieq",roomId:1){
room{
firebaseToken
}
}
}
```
[#165530619](https://www.pivotaltracker.com/story/show/165530619)

#165530619 Update firebase token mutation

---

api/room/schema_query.py
helpers/calendar/events.py

- Currently, there is an existing query that fetches daily events for version 2. The aim of this PR is to refactor the query to get the daily events based on the location of the user making the request.
- Refactor the query to return data based on user location
- Ensure existing tests passes
- Pull this branch `ch-query-daily-events-user-location-v2-165307595`
- Run a new migration to migrate to the V2 database
- Create data in the `rooms` model using `createRoom` mutation. If you need help running these mutations, check out the documentation for the [mrm endpoints](http://localhost:8000/mrm)
- You can have various rooms existing in the room model.
- You may also need to manually seed events into your database to see events specific to the date and location passed in the query.
- After …

#165307595 Query daily events by user location V2

---

api/analytics/analytic_report.py
helpers/calendar/analytics.py
helpers/calendar/analytics_helper.py
helpers/calendar/events.py
helpers/calendar/ratios_and_utilization.py

This PR refactors the method used for getting all events in a room.
Currently, when processing the events in for a given room, all the events in the database are processed.This was making the application to take a lot of time to process analytics requests resulting to HTTP_TIMEOUT error. This PR fixes this by processing only events that have status set to `active` and belongs to the given `room_id` before hand hence reducing the latency in processing the analytics requests.
- git pull and checkout to the branch ch-refactor-analytics-165727957
- You can make use of any analytics query. A sample query has been provided below
```
{
bookingsAnalyticsCount(startDate:"Jan 12 2018", endDate:"Jan 12 2019"){
bookings
period
}
}
```
This query should now be resolved much faster …

#165727957 Refactor Analytics Helper for Getting all Events in a Room

---

api/room/schema.py

Update firebase token mutation for V2.
Modify the Update firebase token mutation to take params of calendar id and firebase token
- Checkout by running `gco bg-update-firebase-token-v2-165530619`
- Make sure to have different rooms already existing in the room model
- Run the following query 
```
mutation{
updateFirebaseToken(firebaseToken:"hakjacjihihaehcfkuqehihjfieq",roomId:1){
room{
firebaseToken
}
}
}
```
[#165530619](https://www.pivotaltracker.com/story/show/165530619)

#165530619 Update firebase token mutation V2

---

.circleci/config.yml
.circleci/deploy_backend_to_kubernetes.sh

- Adds variables for setting up the QA environment
- Use Terraform to create converge infrastructure to be used by QA
testers
[#165955546](https://www.pivotaltracker.com/story/show/165955546)

#165955546 Add variables for the QA environment

---

fixtures/devices/devices_fixtures.py

Fix failing tests due to data difference
When the #435 PR got merged, a test was failing because the test data was different from what was being expected.
3. checkout to branch `bug-fix-failing-test`
3. run tests
N/A
N/A

Re #166409230: Fix failing tests due to data difference

---

api/events/schema.py

modifies events pagination to enable pagination of events per page
- modify event pagination
2. Setup project according to `Readme.md`
3. checkout to branch `ft-paginate-activity-page-166539785`
4. on insomnia to fetch a list of paginated events send the query
```
{
allEvents(startDate: "Mar 11 2019", endDate: "Mar 12 2019", page: 1, perPage: 2) {
day
events {
room {
name
}
eventTitle
endTime
checkedIn
startTime
checkInTime
endTime
cancelled
numberOfParticipants
}
}
hasPrevious
hasNext
queryTotal
pages
}
}
```
[#166539785](https://www.pivotaltracker.com/story/show/166539785)

#166539785 paginate activity page on analytics

---

api/devices/schema.py
tests/test_devices/test_update_device.py

Refactor implementation for updating a device
Currently, when an admin tries to update device information, the `date_added` and `last_seen` fields are updated as well. This behaviour is not what is expected. This PR fixes that issue.
3. checkout to branch `ch-refactor-update-device-mutation-166661313`
4. When using Docker `make migrate`
[#166661313](https://www.pivotaltracker.com/story/show/166661313)
N/A
Screenshots
N/A

#166661313 Refactor Update device mutation

---

.circleci/config.yml

Adds DOMAIN_NAME environment variable to the deployments.
xx
xx
[#CON-123](https://andela-apprenticeship.atlassian.net/browse/CON-123)
xx

CON-123  Add environment variable to the deployment

---

api/room/schema.py
helpers/room/subscriber.py
tests/test_rooms/test_create_room.py
tests/test_rooms/test_delete_room.py
tests/test_rooms/test_update_firebase_token.py
tests/test_subscriber/test_subscriber.py

This pull request ensures requests made to `mrm_push` to manage a room's subscription are asynchronous.
Since this PR is more of a refactoring task, you can verify the mutations/queries concerned are working as before.
```
mutation {
createRoom(
name: "Syne",
calendarId: "andela.com_3836323338323230343935@resource.calendar.google.com",  # noqa: E501
roomType: "Meeting",
capacity: 1,
locationId: 1,
roomTags: [1],
structureId: "b05fc5f2-b4aa-4f48-a8fb-30bdcc3fc968",
imageUrl: "http://url.com",
roomLabels: ["Epic tower", "1st Floor"]) {
room {
name
roomType
capacity
locationId,
calendarId,
structureId,
imageUrl
roomTags {
name
color
}
roomLabels
}
}
}
```
```
mutation  {
deleteRoom(roomId: 1) {
room {
name
capacity
roomType
}
}
}
```
```
mutation  {
updateFirebaseToken(firebaseToken: …
```

CON-138-story Make requests asynchronous with celery

---

jenkins/Jenkinsfile
jenkins/KubernetesPod.yml
jenkins/scripts/build_image.sh
jenkins/scripts/codeclimate_reports.sh
jenkins/scripts/codeclimate_results.sh
jenkins/scripts/create_test_db.sh
jenkins/scripts/deploy_backend_to_kubernetes.sh
jenkins/scripts/mock_test_data.sh
jenkins/scripts/notify_slack.sh
jenkins/scripts/run_tests.sh
jenkins/scripts/set_env_vars.sh
jenkins/scripts/setup_gcloud.sh
jenkins/scripts/upload_coverage.sh

- This pull request sets up a Jenkins pipeline for the converge backend application
- Jenkins build is triggered when any change occurs to the code base
[CON-199](https://andela-apprenticeship.atlassian.net/browse/CON-199?atlOrigin=eyJpIjoiOTAzYjE5OGVlYTcxNDJiY2FlNDA0M2ZmMzNmMDk3MjkiLCJwIjoiaiJ9)

CON-199 Set up jenkins pipeline for the backend application

---

.circleci/config.yml

- This pull request sets up manual CircleCI approval
[CON-279](https://andela-apprenticeship.atlassian.net/browse/CON-279)

CON-279: set up manual approval of the circleci branch

---

helpers/calendar/events.py

Currently, analytics for recurring events are not properly captured as these events are stored in our `DB` as `a single instance of several events`. This precludes the `allAnalytics` and related queries from capturing the recurring/other-instances of such events. This PR ensures recurring events are stored as separate events (with a common `recurring_event_id`) and thus automatically captured by all analytics related queries.
- You can book any of the available test rooms for a recurring event
- Sync your `DB` and all instances of the recurring event are saved. 
- Note that recurring events are capped at 730 instances by the Google Calendar API
[CON-272](https://andela-apprenticeship.atlassian.net/browse/CON-272)

CON-272  Capture recurring events in analytics data
